- escheduler-api/src/main/java/cn/escheduler/api/service/ProjectService.java
1更新项目名时没有做名称唯一性校验
2 建议将项目表名称设置为唯一索引
> 更新项目名时没有做名称唯一性校验

- escheduler-common/pom.xml
- escheduler-common/src/main/java/cn/escheduler/common/utils/HadoopUtils.java
- escheduler-common/src/main/java/cn/escheduler/common/utils/PropertyUtils.java
- pom.xml
现在, ES支持3种不同的存储来存储Resource:
1. HDFS:  本来也支持
2. FILE: 本地文件, 之前代码也支持, 只是需要文档写的更清楚些, 需要修改如下位置:
2.1 修改: common/hadoop/hadoop.properties 的 fs.defaultFS
```
fs.defaultFS=file:///home/escheduler_resource
```
2.2 注意同时修改:  common/common.properties 中的 data.store2hdfs.basepath
```
data.store2hdfs.basepath=/home/escheduler_resource
```
2.3 如果EasyScheduler之前已经创建过租户, 需要额外先创建   /home/escheduler_resource/租户名/resources   文件夹
3. AWS S3,  以及Minio Sever (https://github.com/minio/minio),  通过Minio Server又可以支持: Azure, GCS, NAS等. 以 minio server举例, (AWS S3应该可以直接用, 配置也差不多), 比如: 提前创建了 bucket:  escheduler
3.1 修改: common/hadoop/hadoop.properties 的 
```
fs.defaultFS=s3a://escheduler
fs.s3a.endpoint=http://192.168.199.91:9010
fs.s3a.access.key=A3DXS30FO22544RE
fs.s3a.secret.key=OloCLq3n+8+sdPHUhJ21XrSxTC+JK
```
3.2 …
> close #106 support to store resources in s3a(support aws s3 & minio)

- escheduler-common/src/test/java/cn/escheduler/common/utils/BytesTest.java
Hi
I've written some tests for the methods in `cn.escheduler.common.utils.Bytes` with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.
> Add unit tests for cn.escheduler.common.utils.Bytes

- escheduler-common/src/test/java/cn/escheduler/common/utils/DateUtilsTest.java
Hi
I've written some more tests with the help of [Diffblue Cover](https://www.diffblue.com/opensource), this time for the methods in `cn.escheduler.common.utils.DateUtils`.
As previously, hopefully, these tests will help you detect any regressions caused by future code changes.
> Add unit tests for cn.escheduler.common.utils.DateUtils

- escheduler-common/src/test/java/cn/escheduler/common/utils/JSONUtilsTest.java
I've analysed your codebase and noticed that `cn.escheduler.common.utils.JSONUtils` is not fully tested. I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.
> Add unit tests for cn.escheduler.common.utils.JSONUtils

- escheduler-common/src/main/java/cn/escheduler/common/shell/AbstractShell.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/ProcessInstanceMapperProvider.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/ScheduleMapperProvider.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/TaskInstanceMapperProvider.java
Using `StringBuilder` inside the method has better performance than using `StringBuffer`, because there is no thread safety problem in this case.
So I replacing `StringBuffer` with `StringBuilder` inside the method in this PR.
> Replace StringBuffer with StringBuilder inside the method

- README.md
The old one is still linking to CN doc.
> Fix the en doc link.

- escheduler-common/pom.xml
[BUG][#860] jar包冲突Correct the classpath of your application so that it contains a single, compatible version of javax.servlet.ServletContext
> update escheduler-common pom.xml

- escheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/function/_source/createUdf.vue
The class name with package name will be very long in large projects. It is recommended to increase the maximum length limit to 100(mysql t_escheduler_udfs.class_name is already varchar 255).
> increase udf classname lenth limit

- escheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/localParams.vue
Sometimes the parameters are longer(eg. HDFS path).
Increased to 128(t_escheduler_process_definition.global_params is text and process_definition_json is longtext).
> [Enhancement] increase param length limit

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
Currently, the  batchDeleteProcessDefinitionByIds  & batchDeleteProcessInstanceByIds  (batch operations) has Transaction problems.  
they will make the inner function   deleteProcessDefinitionById  and  deleteProcessInstanceById  not transactional even if they are marked as so.   If those two deleteProcessDefinitionById  and  deleteProcessInstanceById  are  called inside batchDeleteProcessDefinitionByIds  & batchDeleteProcessInstanceByIds  .  so we need to move those batch operation out.
You can refer to https://stackoverflow.com/questions/25738883/spring-transactional-annotation-when-using-try-catch-block
---------
In proxy mode (which is the default), only external method calls coming in through the proxy are intercepted. This means that self-invocation, in effect, a method within the …
> move batchDelete Process Define/Instance Outside for transactional

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
To fix the bug #1399 , The method onlineCreateResource in class ResourcesController，The logger.info has wrong field order with fileName and type. Just swap their order.
-  Edit the ResourcesController.onlineCreateResource method.
> [dolphinscheduler-#1399][bug]fix the wrong order

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
When workgroup referenced by workflow , And there isn’t any instace in
workflow ,the workgroup can be delete . After the workgroup delete , Use the
default workgroup in the page ,Instead of the value id.
- Edit formModel.vue
Add judgment rules for the workgroupId, When the workerGroupId do not match any item in workerGroupsListAll , Set it to -1
> [dolphinscheduler-#184] [enhancement]Use the default workgroup in the page ,Instead of the value id.

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/createTenement.vue
Fix the following error when creating a tenant
`Resolved [org.springframework.web.bind.MissingServletRequestParameterException: Required int parameter 'queueId' is not present]`
create tenant steps. e.g.
- Edit createTenement.vue
> Fix the problem that the 'queueId' is not present when creating a tenant based on the default queue.

- pom.xml
Fix bug #1410 
This pull request jcip-annotations define version information, and maven-assembly-plugin add groupId
- `Add <jcip.version>1.0</jcip.version> and org.apache.maven.plugins to root pom.xml`
> jcip-annotations define version information, and maven-assembly-plugin add groupId

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
For fix the bug #1397 .
Because when create an resource the name will add the suffix, But When rename the resource there is no suffix add to the name, So When update resource name without suffix just like "test.sh" => "test" , Then the bug reproduced.
So  i add the logic bellow:
When rename, if the name without suffix then add it ,else use the origin name.
-  Edit the ResourcesService.javal
> [dolphinscheduler-#1397] [bug]Resources can not be previewed or updated 

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/DataSourceFactory.java
For #1425
JDBC class driver are duplicate define in Constants.java ,such as:
```
public static final String JDBC_POSTGRESQL_CLASS_NAME = "org.postgresql.Driver";
and
public static final String ORG_POSTGRESQL_DRIVER = "org.postgresql.Driver";
```
There are same effect, We can only use one of them.
- *Edit DataSourceFactory.java*
- *Edit Constants.java*
> Remove duplicate JDBC class driver which define in Constants.java 

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
For bug #1379.
Now all datatype use same method ` stmt.setString(index,value);` even DATE and TIMESTAMP.
So i had improved it. If datatype is DATE use `stmt.setDate(index, java.sql.Date.valueOf(value));` ,
if datatype is TIMESTAMP use `stmt.setTimestamp(index, java.sql.Timestamp.valueOf(value));`.i
When use DATE , datatype must use Date and the param format must use `$[yyyy-MM-dd]` , 
When use TIMESTAMP , datatype must use TIMESTAMP and the param format must use `$[yyyy-MM-dd hh:mm:ss]`.
- *Edit ParameterUtils.java*
- *Fix wrong spell in SqlTask.java*
> Improve ParameterUtils.setInParameter, Use Datetype instead of String.

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
fix #1441
username check rule allow contain "."
> add user error when user name contains '.'

- dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/createDataSource.vue
For #1470 .
To improve user experience in datasource page, add default port for each type database.
1. When create or edit datasource, there is a default vaule for port. If user changes type, the default value changes.
2. Use local variables in browser memory, to cache user previous input port for each type. For example :
time-a:  MySQL default  port is 3306 , user change 3306 to 4000.
time-b:  User change type from MySQL to ClickHouse , the port change  from 4000 to 8123.
time-c:  User change type from ClickHouse back to MySQL，the port change from 8123 to 4000，use previous input cache to fillback.
3. In edit datasource page, when the page first loads, use the query value fillback instead of default value.
- *Edit createDataSource.vue*
> [Feature] Improve user experience in datasource page

- sql/dolphinscheduler-postgre.sql
- sql/dolphinscheduler_mysql.sql
- sql/upgrade/1.0.1_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.1.0_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.2.0_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.2.0_schema/postgresql/dolphinscheduler_ddl.sql
- sql/upgrade/1.2.0_schema/postgresql/dolphinscheduler_dml.sql
#	sql/upgrade/1.2.0_schema/mysql/dolphinscheduler_dml.sql
add license header in sql files
*add license in sql files*
*add license in sql files*
> add license in sql files

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/SparkVersion.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/spark/SparkParameters.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/spark/SparkTask.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/spark/SparkTaskTest.java
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/spark.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
*This pull request adds spark task component can swithch spark version*
- *Add spark version param in spark task component*
- *According to the spark Version param specify SPARK_HOME1 or SPARK_HOME2*
- *Add UT for spark task build args*
- *Added SparkTaskTest to verify the change.*
- *Verified in CDH-5.16.2(Spark1.6 and Spark2.4)*
> #839 enhancement : add Spark Task Component can switch Spark Version

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractYarnTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/dependent/DependentTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/http/HttpTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/processdure/ProcedureTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/python/PythonTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/shell/ShellTask.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/dependent/DependentTaskTest.java
This pull request is mainly fix the bug of AbstractTask class;
when the task is executed by TaskScheduleThread, task.handle () will be called to trigger the execution logic of the task itself. If the task throw a exception, it will capture and call the kill () method to kill the task and set the task status to failed 
However, when each task subclass overrides the handle () method, it chooses to catch the exception itself and print the error log without throwing it. 
This will cause the TaskScheduleThread thread to execute task but can't catch the task exception forever. The logic of killing the task cannot be triggered forever, and the completion status of the task may not be set correctly.
add throw e to subclass of AbstractTask
This pull request is bug fix without any test coverage.
> fix AbstractTask's handle method exception

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/queue/ITaskQueue.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/queue/TaskQueueZkImpl.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterBaseTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java
fix issue:1477 some tasks would be running all the time when db delayed
- split the submit to two part: submit to db and submit to queue.
- while(true) retry submit task to db and queue.
server model is difficult for ut because some db operations. there maybe some refactors in the feature.
> fix issue:1477 some tasks would be running all the time when db delayed(#1477)

- dolphinscheduler-dist/dolphinscheduler-backend/src/main/release-docs/LICENSE
*add Apache 1.1 licenses statistic for commons-el 1.0*
*add Apache 1.1 licenses statistic for commons-el 1.0*
> add Apache 1.1 licenses statistic for commons-el 1.0

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/MonitorService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/ZookeeperMonitor.java
- dolphinscheduler-common/pom.xml
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/queue/TaskQueueZkImpl.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/Preconditions.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/AbstractListener.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/AbstractZKClient.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/DefaultEnsembleProvider.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/ZookeeperCachedOperator.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/ZookeeperConfig.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/ZookeeperOperator.java
- dolphinscheduler-common/src/main/resources/zookeeper.properties
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/zk/ZKMasterClient.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/zk/ZKWorkerClient.java
the main purpose of this pr is to refactor the dependency on zk, including zk config dependency & zk client dependency. 
In the process of refactoring, I have tried to be compatible with the previous code as much as possible, but still involves more file changes, so here are some important points that need to be explained for the convenience of code review
1. the main purpose of this refactor is to leave the zk configuration and zk client to the spring container for management, but in order to be compatible with the implementation of TaskQueueZkImpl (all references to this class are static methods), so conf file: zookeeper.properties is still retained.
2. As mentioned above, all methods that reference the TaskQueueZkImpl class are static methods. If refactor it, more files will be …
> refactor zk client and zk config module

- .github/workflows/ci_ut.yml
Fix SonarCloud 0% UT coverage on new code.  issue #1611
Changes with maven command :
1. Remove org.jacoco:jacoco-maven-plugin:prepare-agent .
2. Replace  org.sonarsource.scanner.maven:sonar-maven-plugin:sonar to org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar .
Report at https://sonarcloud.io/dashboard?id=dolphinscheduler with 13.5% coverage .
> fix 0% UT coverage on new code.  issue #1611

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/queue/TaskQueueZkImpl.java
*Fixed the issue that tasks_queue and tasks_kill did not exist in zookeeper*
- *Add create tasks node logic to TaskQueueZkImpl.java*
> Fixed tasks_queue and tasks_kill did not exist in zookeeper #1696

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/http.vue
- dolphinscheduler-ui/src/js/conf/home/store/dag/mutations.js
- dolphinscheduler-ui/src/js/conf/home/store/dag/state.js
This pull request will finish the subtask architecture and http in  #1675. 
It will improve the user experience in the task definition page.
When we set up the task param, it can automatically cache the input. When we change task instance or cancel the task window without reloading the browser, the previous value will fillback after we open the task window again.
- *Edit state.js*
- *Edit mutations.js*
- *Edit dag.vue*
- *Edit http.vue*
> Improve the user experience in the task definition page, define the architecture and implement http.vue

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/FetchTaskThread.java
In FetchTaskThread.run method, checkWorkerGroup invoke after "queryUserQueueByProcessInstanceId", why not just after getTaskInstanceDetailByTaskId
if checkWorkerGroup check failed , the rest of the logic can be ignored
checkWorkerGroup invoked after getTaskInstanceDetailByTaskId
if (verifyTaskInstanceIsNull(taskInstance)) {
logger.warn("remove task queue : {} due to taskInstance is null", taskQueueStr);
removeNodeFromTaskQueue(taskQueueStr);
continue;
}
if(!checkWorkerGroup(taskInstance, OSUtils.getHost())){
continue;
}
> https://github.com/apache/incubator-dolphinscheduler/issues/1743
> why not invoke checkWorkerGroup in advance 

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/datasource.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sql.vue
- dolphinscheduler-ui/src/js/conf/home/store/dag/actions.js
This PR is a subtask of #1675.
Implements the sql type task, now it can be cache the previous input.
- *Edit actions.js*
- *Edit datasource.vue*
- *Edit sql.vue*
> Implements the sql type task, now it can be cache the previous input.

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/queue/ITaskQueue.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/queue/TaskQueueZkImpl.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/ZookeeperOperator.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/queue/TaskQueueZKImplTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/FetchTaskThread.java
In FetchTaskThread.run method ,using getAllTasks to determine if there is a task，why not using "hasTask"
1、ITaskQueue add "boolean hasTask(String key)" function
2、ZookeeperOperator add “public boolean hasChildren(final String key)” fuction
public boolean hasChildren(final String key){
try {
Stat stat = zkClient.checkExists().forPath(key);
return stat.getNumChildren() >= 1;
} catch (InterruptedException ex) {
logger.error("hasChildren key : {} InterruptedException", key);
throw new IllegalStateException(ex);
} catch (Exception ex) {
logger.error("hasChildren key : {}", key, ex);
throw new RuntimeException(ex);
}
}
> https://github.com/apache/incubator-dolphinscheduler/issues/1742
> ITaskQueue should have "hasTask" function

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
fix bug #1779 The execution of the SUB_PROCESS task failed first, but eventually succeeded
> [bug fix] #1779 The execution of the SUB_PROCESS task failed first, but eventually succeeded

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorService2Test.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ScheduleMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ScheduleMapper.xml
- dolphinscheduler-server/pom.xml
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ScheduleUtils.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/MasterExecThreadTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/ScheduleUtilsTest.java
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/start.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
- pom.xml
#1550 fix feature: Supplementary data with schedule
When the task complement is run, a execution plan list is generated according to the scheduling plan. If the execution plan list is not empty, it is scheduled according to the plan list. If the execution plan is empty, it is executed daily.
for parallel run
- edit dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
for serial run
- edit dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
dao
- edit dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
- edit dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ScheduleMapper.java
- edit …
> Supplementary data by schedule

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ResourceMapper.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ResourceMapper.xml
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapper.xml
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ResourceMapperTest.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapperTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/UDFUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskScheduleThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
*when the executor of process instance is not the owner of udf resouce, the path of the read resource file is incorrect*
*when the executor of process instance is not the owner of udf resouce, the path of the read resource file is incorrect*
- *Add listUdfByResourceId in UdfFuncMapper*
- *update  testGrantResources in UsersServiceTest.*
- *Added testListUdfByResourceId in UdfFuncMapperTest.*
> [fix #1828] when the executor of process instance is not the owner of udf resouce, the path of the read resource file is incorrect

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
The constructor has passed in an taskAppId, no need to get from taskAppId.
```
public AbstractCommandExecutor(Consumer<List<String>> logHandler,
String taskDir, String taskAppId,int taskInstId,String tenantCode, String envFile,
Date startTime, int timeout, Logger logger){
this.logHandler = logHandler;
this.taskDir = taskDir;
this.taskAppId = taskAppId;
this.taskInstId = taskInstId;
this.tenantCode = tenantCode;
```
> fix: get taskAppId bug

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/plugIn/jsPlumbHandle.js
Fix bug #1986 
When in the projects define page, click the toolbar's button(task type) will cause the task details window switch to new one.
For now, the task details window will not switch.
- *Edit jsPlumbHandle.js*
- *Edit dag.vue*
> Fix bug #1986.

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/datax.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/python.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/shell.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sql.vue
1. add input cache for datax task
2. add cache for codemirror component which include python, shell and sql task.
- *datax.vue*
- *python.vue*
- *shell.vue*
- *sql.vue*
> [newfeature] Add input cache for datax task and codemirror component

- dolphinscheduler-api/pom.xml
- dolphinscheduler-server/pom.xml
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/zk/DefaultEnsembleProvider.java
- dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/zk/DefaultEnsembleProviderTest.java
- pom.xml
https://github.com/apache/incubator-dolphinscheduler/issues/2020
the curator issue: https://github.com/apache/curator/pull/297  may cause InterProcessMutex.acquire() hang, we'd better upgrade its version
> Upgrade curator version

- .github/workflows/ci_backend.yml
- .github/workflows/ci_e2e.yml
- .github/workflows/ci_frontend.yml
- .github/workflows/ci_ut.yml
add those code for all 4 workflow
```
- name: checkout submodules
shell: bash
run: |
git submodule sync --recursive
git -c protocol.version=2 submodule update --init --force --recursive --depth=1
```
> fix actions/checkout@v2 problem

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/Command.java
Command.java
`import com.sun.org.apache.regexp.internal.RE;`
The class is unused and cannot be built in jdk11.
> fix: remove redundant import class #2109

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/process/ProcessImplForWin32.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/shell/ShellTaskTest.java
Current implementation relies on `sun.misc.JavaIOFileDescriptorAccess`
which is only accessible on oraclejdk8.
Basically the demand is getting & setting `handle` field of `FileDescriptor`,
so we can directly do that with reflection.
Though, I suspect the necessity we introduce ProcessImplForWin32. Maybe
we could have a better way to support worker server to run bat script.
Replace `JavaIOFileDescriptorAccess` with reflections to `FileDescriptor`.
This pull request is already covered by existing tests, such as
- `ProcessImplForWin32Test`
This closes #2111 .
> access field handle of FileDescriptor in ProcessImplForWin32 by reflection for portability

- .github/workflows/ci_ut.yml
with checkout V2, sonar analysis get warning like:
```
...
[WARNING] Missing blame information for the following files:
[WARNING]   * dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/ExecuteTaskResponseCommand.java
[WARNING]   * dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/CommandType.java
[WARNING]   * dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java
[WARNING]   * dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/ExecuteTaskRequestCommand.java
[WARNING] This may lead to missing/broken features in SonarCloud
...
```
and then sonar analysis get the wrong coverage for PR
1. add both push and pull request for ui_ct workflow.
2. upload coverage report …
> fix wrong sonar analysis coverage with checkout V2.

- dockerfile/Dockerfile
- dockerfile/hooks/check
- dockerfile/startup.sh
1. add tini
2. replace `tee` command by `tail` command in **startup.sh**
3. api-server need to support zookeeper
> docker run failed when docker command was `docker run -d`

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
> Toolbar of the DAG has not prompt

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/process/ProcessImplForWin32.java
when running windows bat script, the handle is invalid in win7
#2268
> when running windows bat script, the handle is invalid in win7

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/ConnectionFactory.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/UpgradeDao.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/AlertDaoTest.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ConnectionFactoryTest.java
Return java.sql.DataSource to decouple DruidSource. And cache DataSource instance.
*(or)*
(or)
*(example:)*
> Decouple DruidDataSource in ConnectionFactory and cache DataSource instance

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/index.vue
Because there are not many fields in the job definition page, it is currently fixed, and the workflow instance page has scrolling
> Work example page list supports scrolling #2554

- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
fix bug: sub worker flow in complement data would run start date (#2581)
> [bug fix] sub worker flow in complement data would only run start date

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/config/MasterConfig.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumer.java
- dolphinscheduler-server/src/main/resources/master.properties
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumerTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThreadTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/registry/DependencyConfig.java
fix bug(#2762): master would be blocked when worker group not exists
1. master would not dispatch one task in loop.
2. master would put the failure tasks in the queue again.
> [BUF FIX]fix: the master would be blocked when worker group not exists

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ExecutionStatus.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/DependentTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/DependentExecute.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/DependentTaskTest.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
fix bug(#2464) dependent task failed when conditions task exists
depend all: we should only see the process instance state,  do not care about the tasks state.
> [BUG FIX] fix bug: dependent task failed when conditions task exists

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
*when init workflow, the tenantId linked by the tenantId of user*
- Modify dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
- when init workflow, the tenant info is "default", developer need to switch tenant, but the tenant always linked by tenantid of login user in most scenarios
> when init workflow, the tenantId linked by the tenantId of login user

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/SchedulerService.java
*Return ProcessDefinition ID when call ProcessController.createProject.
*Return Scheduler ID when call SchedulerController.createScheduler.
Client system need the created object ID to bind the relationship between client system and Dolphinscheduler system.
*changed source files:
-dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
-dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/SchedulerService.java
> Return ProcessDefinition ID, Scheduler ID when call the corresponding creation APIS

- .github/workflows/ci_ut.yml
- pom.xml
Set up JDK 11 for SonarCloud after the unit test is executed.
Modify mvn command to JDK 11 version.
> Set up JDK 11 for SonarCloud in github action.

- ambari_plugin/common-services/DOLPHIN/1.3.0/package/scripts/dolphin_alert_service.py
- ambari_plugin/common-services/DOLPHIN/1.3.0/package/scripts/dolphin_api_service.py
- ambari_plugin/common-services/DOLPHIN/1.3.0/package/scripts/dolphin_logger_service.py
- ambari_plugin/common-services/DOLPHIN/1.3.0/package/scripts/dolphin_master_service.py
- ambari_plugin/common-services/DOLPHIN/1.3.0/package/scripts/dolphin_worker_service.py
when using function  Execute the arguments user and sodo  don`t support to be setted at the same time
> [bugfix] remove Conflicting configuration sudo and user

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/shell/AbstractShell.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/LoggerUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/OSUtilsTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/log/TaskLogFilter.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
*Init task logger before init TaskExecuteThread and pass the `taskLogger` in to TaskExecuteThread init method as parameter, so we can record the user and work dir creating log to task instance log, and user can read this log in front-end WebUI.* #3014 
*Use common ShellExecutor in FileUtils.* #2925 
- *Add `taskLogger` parameter  to TaskExecuteThread.* 
- *Add three log utils to LoggerUtils.*
- *Init task logger before create initing TaskExecuteThread, and init task logger process to TaskExecuteProcessor.*
- *Log all detail when create user and working dir in FileUtils.*
> [Feature-2925][server] Init TaskLogger in TaskExecuteProcessor (#2925)

- ambari_plugin/common-services/DOLPHIN/1.3.0/alerts.json
- ambari_plugin/common-services/DOLPHIN/1.3.0/metainfo.xml
1. fix alert.json includes repeated tag 'DOLPHIN_ALERT' 2. metainfo.xml The version number of the RPM package is no longer specified in the metainfo.xml
> [bugfix] fix alert.json and metainfo.xml bugs 

- sql/create/release-1.0.0_schema/mysql/dolphinscheduler_ddl.sql
- sql/dolphinscheduler_mysql.sql
- sql/upgrade/1.0.2_schema/mysql/dolphinscheduler_ddl.sql
*Fix the mysql version and datetime sql syntax limited error for 5.5x - 5.64.*
- *Remove the CURRENT_TIMESTAMP in sql file.*
- *Change the sql datetime(0) syntax to common syntax datetime, because mysql5.5x does not support the datetime(0) syntax, and datetime syntax is be in common use in mysql5.x and mysql8.x.*
- *There is no need to set datetime in java code, because the default time was set up before.*
> [Feature-2127][sql-schema] Fix the mysql version limited error (#2127)

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/HiveDataSource.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/datasource/HiveDataSourceTest.java
- pom.xml
fix the bug #2923 
*This pull request fix the bug #2923*
Corrected the connection string of hive jdbc link string. If the parameter in the link string is the configuration parameter in hive-default.xml, add it before the parameter ?.
<br>
> see the hive Connection URLs - Connection URL Format
[HiveServer2Clients-ConnectionURLs](https://cwiki.apache.org/confluence/display/Hive/HiveServer2+Clients#HiveServer2Clients-ConnectionURLs)
```
Connection URLs
Connection URL Format
The HiveServer2 URL is a string with the following syntax:
jdbc:hive2://<host1>:<port1>,<host2>:<port2>/dbName;initFile=<file>;sess_var_list?hive_ …
```
> [Bug 2923] Hive JDBC connection parameter ignored

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistry.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryTest.java
fix #3187 
Close Heartbeat thread pool when MasterRegistry unRegistry.
Add unit test
*(or)*
(or)
*(example:)*
> [Bug-3187]close Heartbeat thread pool when MasterRegistry unRegistry

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/MailUtils.java
- *Set the system property of "mail.mime.splitlongparameters" is false in the class "org.apache.dolphinscheduler.alert.utils.MailUtils"*
This pull request is already covered by existing tests.
local test method : org.apache.dolphinscheduler.alert.utils.MailUtilsTest#testSendMails
situation one: Chinese 100.    result: success
situation two: Chinese 100 + English 100.   result: success
other situation: Whether I set this property or not, and whether the name contains Chinese or not.when the length of  attachment is too long, the mail will send failed. ( i have been test the situation that the length is 500, but i'm not sure the max length,because the exception is thrown by a native method)
> [BUG#2359][Alert] Mail Chinese name is too long garbled

- dolphinscheduler-server/src/main/resources/worker.properties
- script/scp-hosts.sh
*when execute install script*
*when execute install script*
*modfy config/install_config.conf*
workers="ds1:default,ds1:test,ds2:default"
The worekr ds1 will belongs default and test workergoups.
> [Feature][server]support one worker can belongs different worker group when execute install script

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
fix bug #1336
serial complement data can have multiple process instances
> [FIX-1336] [master] serial complement data can have multiple process instances

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
bug fix(#1336 )set start/end time before complement next process
*(or)*
(or)
*(example:)*
> [FIX-1336] [master] serial complement data can have multiple process instances 

- style/intellij-java-code-style.xml
*Add code import style automatic formatter for `idea`, it can automaticly help contributor to format the import to avoid a lot of changes about java code import*
- *Add `intellij-java-code-style.xml`l*
> [Improvement][style] Add code import style automatic formatter

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
close(#3338 )
*Fix the warning when user do not fill the node blank*
- *Format the `Please enter name(required)` to `Please enter name (required)`*
> [Fix-3338][ui] Fix the warning when user do not fill the node blank

- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumerTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/registry/ZookeeperNodeManagerTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/processor/TaskCallbackServiceTest.java
- pom.xml
add CuratorZookeeperClient springContextConfig
What is the purpose of the pull request
this closes #3314 
add CuratorZookeeperClient springContextConfig
When I started the TaskPriorityQueueConsumerTest class, he encountered the following exception
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name'nettyExecutorManager': Unsatisfied dependency expressed through field'zookeeperNodeManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name ' zookeeperNodeManager': Unsatisfied dependency expressed through field'registryCenter'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name'zookeeperRegistryCenter': …
> [Test][server] Fix Test ContextConfiguration error.

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapperTest.java
close (#3191)
* add function in ProcessInstanceController.java , ProcessInstanceService.java , ProcessInstanceMapper.java
* add some test in ProcessInstanceServiceTest.java , ProcessInstanceMapperTest.java
* add some constant/status in Status.java , Constants.java
* add some sql in ProcessInstanceMapper.xml
Manually verified the change by testing locally.
> add feature : query top n success process instance order by running duration

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/spark/SparkParameters.java
*#3397 cancel spark task version check*
- *cancel spark task version check*
- *when there is no sparkversion field in process denifiton json, the submit of spark task is used by default to submit SPARK2_HOME*
> [fix-bug #3397]cancel spark task version check

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/cache/impl/TaskInstanceCacheManagerImpl.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/cache/impl/TaskExecutionContextCacheManagerImpl.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
*This pull request fix the spell error 、add log in SqlTask and add null judgment in SqlTask*
- *none*
*none*
> [Fix] [Server] Fix the spell error and add log in SqlTask

- docker/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
- docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
- docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
add ZOOKEEPER_ROOT env in k8s deploy
- modified:   docker/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
- modified:   docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
- modified:   docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
> [Fix][server&api&worker] Fix add ZOOKEEPER_ROOT env in k8s deploy

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/DolphinSchedulerManager.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/ResourceDao.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/UpgradeDao.java
- sql/upgrade/1.3.2_schema/mysql/dolphinscheduler_ddl.sql
- sql/upgrade/1.3.2_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.3.2_schema/postgresql/dolphinscheduler_ddl.sql
- sql/upgrade/1.3.2_schema/postgresql/dolphinscheduler_dml.sql
[Fix-3423][dao][sql]Fixed that the resource file of the task node can't 't be found when upgrade from 1.2.0 to 1.3.2
*[Fix-3423][dao][sql]Fixed that the resource file of the task node can't 't be found when upgrade from 1.2.0 to 1.3.2
*Fixed that the resource file of the task node can't 't be found when upgrade from 1.2.0 to 1.3.2*
- *add ResourceDao*
- *add 1.3.2 schema*
- *add the judge of whether the workerGroupId is null*
> [Fix-3423][dao][sql]Fixed that the resource file of the task node can't 't be found when upgrade from 1.2.0 to 1.3.2

- dolphinscheduler-api/pom.xml
the ds use curator-client:4.3.0 dependency by curator-frameworke,
but hadoop-common use  curator-client:2.7.1,
so make the ClassNotFoundException
```
Caused by: java.lang.ClassNotFoundException: org.apache.curator.connection.StandardConnectionHandlingPolicy
```
exclude curator-client in hadoop-common to resolve this
> resolve curator-client dependency confliction 

- .gitignore
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
- dolphinscheduler-common/pom.xml
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/DbType.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/BaseDataSource.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/DataSourceFactory.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/PrestoDataSource.java
- dolphinscheduler-dist/release-docs/LICENSE
- dolphinscheduler-dist/release-docs/NOTICE
- dolphinscheduler-dist/release-docs/licenses/LICENSE-presto-jdbc.txt
- dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/createDataSource.vue
- dolphinscheduler-ui/src/js/conf/home/store/dag/state.js
- dolphinscheduler-ui/src/js/conf/home/store/datasource/actions.js
- pom.xml
- tools/dependencies/known-dependencies.txt
update .gitigonre to igonre some files
add presto datasource support
``` log
new file:   dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/PrestoDataSource.java
modified:   .gitignore
modified:   dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
modified:   dolphinscheduler-common/pom.xml
modified:   dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
modified:   dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/DbType.java
modified: …
```
> [Feature]add presto datasource support

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/registry/ZookeeperNodeManager.java
*fix issue: #3480*
*ds muti-level directory in zk, which lead to fail to assign work. for example set zookeeper.dolphinscheduler.root=/path/to/dolphinscheduler*
> [bug-3480][server]fix ds muti-level directory in zk, which lead to fail to assign work

- docker/build/Dockerfile
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProjectService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataAnalysisServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorService2Test.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/SchedulerServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskInstanceServiceTest.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Project.java
*Introduce ProjectService interface for clear code and make the function visibility of ProjectService more clear*
- *Add `ProjectService` and `ProjectServiceImpl`*
- *Add Builder design pattern for `Project`*
> [Improvement-3369][api] Introduce ProjectService interface for more clear code

- .github/workflows/ci_ut.yml
Integrate checkstyle result into CI, just for modified code of PR . #3517 
Added a checkstyle job in github action ci_ut.yml file. 
Use reviewdog to post checkstyle result as comments for PRs.
Tested at [1]
[1] https://github.com/Jave-Chen/incubator-dolphinscheduler/pull/23/files
> [Improvement-3517][CI] Integrate checkstyle result into CI, just for modified code of PR 

- docker/build/Dockerfile
*Fix e2e ci docker image build error*
- *change dockerfile python version*
> [Hotfix][ci] Fix e2e ci docker image build error for 1.3.2-release

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
*[Fix-3536][api]If user didn't have tenant,create resource directory will NPE*
*Fix the issue that If user didn't have tenant,create resource directory will NPE*
> [Fix-3536][api]If user didn't have tenant,create resource directory will NPE

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstance.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/entity/TaskInstanceTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/ConditionsTaskTest.java
- pom.xml
refactor the unit test for ConditionsTask
- refactor and enable the unit test for ConditionsTask
- add FAILURE dependence test for ConditionsTask
- fix a potential NPE at TaskInstance.getDependence and add a unit test for it
- enable unit test for TaskInstance
- Updated `org.apache.dolphinscheduler.server.master.ConditionsTaskTest`
- Updated `org.apache.dolphinscheduler.dao.entity.TaskInstanceTest`
- Tested locally
> [Improvement][dao,server] unit test for ConditionsTask

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/AlertManager.java
fix #3299
Json string parsing problem caused by non-standard json format.
Fixed alert cannot be notified，when master or worker shutdown。
I think the reason for this is that Jackson can't parse JSON fields with single quotes.
The main reason is that the strings stored in the database are not in the standard JSON format.
fix before :
fix after ：
> [Fix-3299][dao&server] Fix 3299,when Json string parsing problem caused by non-standard json format.

- style/intellij-java-code-style.xml
*Add sign next line automatic assigner for code style*
*For example:*
It can generate string like this one, it can match the rules of `checkstyle`
```java
String json = "{\"a\":"
+  \"b\"}";
```
not like this one
```java
String json = "{\"a\":"+ 
\"b\"}";
```
> [Improvement][code style] Add sign next line automatic assigner

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/ProcessUtilsTest.java
server model ProccessUtils.java code cleaning.
1.Remove unreferenced variables
2.Remove unnecessary throws exception type.
> [Improvement][server] server model ProcessUtils.java code cleaning.

- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/SubProcessTaskTest.java
- pom.xml
- Yet another workaround to truly do unit test in a scope of `Stopper.isRunning()`.
- Compared with #3587 
- Add a test for SubProcessTaskExecThread and enable it in `pom.xml`
- Use `PowerMockRunner` to mock static class `Stopper`
- Added `org.apache.dolphinscheduler.server.master.SubProcessTaskTest`
- Tested locally.
> [Improvement][server] unit test for SubProcessTask with PowerMockRunner

- docker/build/conf/zookeeper/zoo.cfg
add config to enable dolphinscheuler monitor data
```
#Four Letter Words commands:stat,ruok,conf,isro
4lw.commands.whitelist=*
```
if without this config,the monitor data is all  default value -1
> add 4lw.commands.whitelist for ds monitor

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/ConditionsTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/DependentTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterBaseTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/LogUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThreadTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/LogUtilsTest.java
- pom.xml
- Refactor code for getTaskLogPath to reduce NPE log during UT
- Add `org.apache.dolphinscheduler.server.utils.LogUtils`
- Remove `MasterBaseTaskExecThread.getTaskLogPath`
- Remove `org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.getTaskLogPath`
- Added `org.apache.dolphinscheduler.server.utils.LogUtilsTest`.
- Tested locally.
> [Improvement][server] Refactor code for getTaskLogPath to reduce NPE log during UT

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java
- dolphinscheduler-common/src/main/resources/common.properties
Improvement #3690
The current policy is to take the first one, but the first test is not fixed。This is my debug screenshot.
---
当前策略是取第一个，但是第一个测试下来也是不固定的，这个是我调试截图。
The problem is that on the server, the acquired IP is the external network card IP.External network control is more strict, so it is not a full port through. Therefore, it is recommended to get IP of Intranet card first.So make logical optimizations in your code.
---
遇到的问题是服务器上，获取的ip为外网网卡ip.外网控制比较严格，所以不是全端口打通。所以，建议优先获取内网网卡ip。
所以做出代码中的逻辑优化。
> [Improvement-3690][common] Get the native IP policy problem (获取本机ip策略问题 )

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/TaskParametersUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/TaskManagerTest.java
- pom.xml
this closes #3383
What is the purpose of the pull request
[server] WATERDROP task plug-in optimization in switch case code cleaning.
Brief change log
Clean up duplicate code
Verify this pull request
> [Improvement][server] WATERDROP task plug-in optimization in switch case code cleaning.

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/util.js
#3720
mailbox input is illegal,js mailbox verification fix.
Source location：dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/util.js
```
/^([a-zA-Z0-9]+[_|\-|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\-|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/ // eslint-disable-line
change
/^([a-zA-Z0-9]+[_|\-|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\-|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,}$/ // eslint-disable-line
```
> [Improvement-3720][ui] js mailbox verification fix

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
#3707 
Workflow definition and batch deletion of workflow instance pages
1.Click the batch delete button, the cancel click in the prompt box has no effect
2.After the batch delete is successful, the batch delete button is displayed in a clickable state. Normally, it cannot be clicked. You should delete the records first before clicking the batch delete.
definition list.vue
instance list.vue
---
工作流定义和工作流实例页面批量删除功能
1.点击批量删除按钮，提示框内的取消点击没有效果
2.批量删除成功后，批量删除按钮展示还是可点击状态，正常是不可以点击的，应该先删除记录，才可以点击批量删除。
> [Fix-3707][ui] The batch delete function in the workflow definition and workflow instance pages cannot be canceled if selected

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
#3693
Change the display state of batch operation buttons in the workflow definition and instance, and click the state when the specific workflow definition or instance is not selected.
definition list.vue add button disabled
instance list.vue add button disabled
---
##拉取请求的目的是什么
工作流定义和实例中更改批量操作按钮展示状态，不选中具体工作流定义或实例的时候禁止点击状态。
##简要更改日志
definition list.vue添加按钮已禁用属性
instance list.vue添加按钮已禁用属性
##验证此拉取请求
此更改增加了测试，可以进行如下验证：
-*通过本地测试手动验证更改。*
> [Improvement-3693][ui] definition and instance bulk action buttons show changes

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/TaskParametersUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/TaskManagerTest.java
#3745 
```
switch (EnumUtils.getEnum(TaskType.class,taskExecutionContext.getTaskType()))
```
When the task type does not exist in the enumeration class TaskType, EnumUtils.getEnum() returns null, and switch will report a null pointer exception
1.TaskParametersUtils  switch tasktype param is not null
1.TaskManager switch tasktype  param is not null
TaskParametersUtilsTest
TaskManagerTest
> [fix-3745][server] server get tasktype NPE exception

- tools/dependencies/check-LICENSE.sh
- impl #3750 
- use `find` + `sed` instead of `ls` to fix the problem.
- No test case cover it, so you should run the script manually.
> [Fix-3750][tools] check-LICENSE.sh: support sub dirs in dist/lib

- docker/build/hooks/build.bat
*[Fix-#3124][docker]Fix that can not build a docker image on windows*
*[Fix-3124][docker]Fix that can not build a docker image on windows*
- *get version through read version of the pom.xml file*
> [Fix-3124][docker]Fix that can not build a docker image on windows

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
*[Fix-#3713][common]Fix that catfile method Stream not closed*
> [Fix-#3713][common]Fix that catfile method Stream not closed

- ambari_plugin/common-services/DOLPHIN/1.3.0/package/scripts/dolphin_api_service.py
- sql/upgrade/1.3.3_schema/mysql/dolphinscheduler_ddl.sql
fix bug(#3845 ) Start Ambari report an error: Table 't_ds_process_definition_version' already exists
> [FIX-Bug #3845][Ambari Plugin] Start Ambari report an error: Table 't_ds_process_definition_version' already exists

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
this branch merge to branch 1.3.3-release (#3864  branch merge to branch dev)
#3843
problem:
The workflow definition name already exists, saved workflow ，prompt: update workflow definition error
The reason for this problem is that the user tenant or queue or project is empty. When the workflow definition is saved, the verification of the workflow definition name fails, the projectId and processDefineName construct unique constraints, and the workflow update fails when the data is saved.
I think that the workflow definition name verification only needs to verify the existence of projectId and processDefineName,The original query method is called in many places without modification.
```
select pd.*,u.user_name,p.name as project_name,t.tenant_code,t.tenant_name,q.queue,q.queue_name
from …
```
> [1.3.3-release][fix-3843][api] When the update workflow definition name already exists, the prompt is not friendly add process define name verify. 

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
#3843 
problem:
The workflow definition name already exists, saved workflow ，prompt: update workflow definition error
The reason for this problem is that the user tenant or queue or project is empty. When the workflow definition is saved, the verification of the workflow definition name fails, the projectId and processDefineName construct unique constraints, and the workflow update fails when the data is saved.
I think that the workflow definition name verification only needs to verify the existence of projectId and processDefineName,The original query method is called in many places without modification.
```
select pd.*,u.user_name,p.name as project_name,t.tenant_code,t.tenant_name,q.queue,q.queue_name
from t_ds_process_definition pd
JOIN t_ds_user u ON pd.user_id = u.id
JOIN …
```
> [fix-3843][api] When the update workflow definition name already exists, the prompt is not friendly add process define name verify.

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingClient.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingServer.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/CommandType.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/config/NettyClientConfig.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/handler/NettyClientHandler.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/handler/NettyServerHandler.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/Constants.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/NettyUtils.java
*[FIX_#3789][remote]cherry pick from dev to support netty heart beat*
*([FIX_#3789][remote]cherry pick from dev to support netty heart beat*
> [FIX_#3789][remote]cherry pick from dev to support netty heart beat

- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
because queryProcessInstanceListPaging has contain longtext type field by instance.*,so queryProcessInstanceListPaging query slow , but longtext field not used.
*(or)*
(or)
*(example:)*
- …
> [Improvement][dao] queryProcessInstanceListPaging query slow

- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
because queryTaskInstanceListPaging  has contain longtext  type field  by instance.*,so  queryTaskInstanceListPaging query slow , but longtext  field not used.
*(or)*
(or)
*(example:)*
- …
> [Improvement][dao] queryTaskInstanceListPaging query slow

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/createTenement.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
#3835 
When the tenant name contains "<", when creating/editing users and saving workflows, the tenant drop-down list data is blank
add verify tenant name cannot contain special characters.
```
let isSpecial = /[~#^$@%&!*()<>《》:;'"{}【】	]/gi
if (isSpecial.test(this.tenantName)) {
this.$message.warning(`${i18n.$t('Please enter tenant name without special characters')}`)
return false
}
```
> [fix-3835][ui] When the tenantName contains "<", the tenant drop-down list is blankadd verify tenant name cannot contain special characters.

- docker/build/Dockerfile
- docker/build/startup.sh
Signed-off-by: Youngman <bushengquan@gmail.com>
*This pull request fix startup.sh variables cannot reference in single quotes. (#3894)*
- *Fix docker/build/startu.sh a variables without single quotes (#3894)*
- *Add mysql-client in Dockerfile to support  mysql as backend database.*
*(or)*
(or)
*(example:)*
- …
> [Fix][Docker] fix startup.sh variables cannot reference in single quotes.

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
fix bug(#3615 ):After the task is executed successfully, After the task is executed successfully, but the next task has not been submitted, stop the master，the workflow will fail
> [FIX-3615] master exit  gracefully 

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
*[fix-3843][api] When update workflow definition,if name already exists, the prompt is not friendly*
*When update workflow definition,if name already exists, the prompt is not friendly*
- *add verify whether process definition name exists in the update method*
> [fix-#3843][api] When update workflow definition,if name already exists, the prompt is not friendly

- sql/dolphinscheduler_mysql.sql
this pull request fix import dolphinscheduler_mysql.sql insert admin user data error
INSERT INTO `t_ds_user` VALUES ('1', 'admin', '7ad2410b2f4c074479a8937a28a22b8f', '0', 'xxx@qq.com', '', '0', '2018-03-27 15:48:50', '2018-10-24 17:40:22', null, 1);
to
INSERT INTO `t_ds_user` VALUES ('1', 'admin', '7ad2410b2f4c074479a8937a28a22b8f', '0', 'xxx@qq.com', '', '0', '2018-03-27 15:48:50', '2018-10-24 17:40:22', null); 
this close  #3994 
version  1.3.3-release
> [Fix-#3994 ][sql-script] Pull Request fix import dolphinscheduler_mysql.sql insert admin user data

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java
> [Fix-4090][dao] Add null judgment

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sqoop/generator/sources/MysqlSourceGenerator.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sqoop/generator/targets/MysqlTargetGenerator.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/sqoop/SqoopTaskTest.java
*fix  #4104  sqoop import fail when jdbc string contains special char*
- *modify sqoop mysql source and mysql target*
This pull request is already covered by existing tests, such as *SqoopTaskTests*.
> [FIX-4104]fix sqoop task jdbc string contains special char

- dolphinscheduler-api/src/main/resources/application-api.properties
*enable response resources gzip compression*
- reduce response resources' transfer size
- improve access speed and user experience
- *enable response resources gzip compression*
The screenshot of effect before the gzip compression is as follow:
The screenshot of effect after the gzip compression is as follow:
> [Feature][API]enable response resources gzip compression

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sqoop/SqoopConstants.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sqoop/generator/targets/HiveTargetGenerator.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/sqoop/SqoopTaskTest.java
*#4135 split hive database and table when RMDBS improt to HIve*
- *Modify Sqoop HiveTargetGenerator.class*
This pull request is already covered by existing tests, such as *worker/SqoopTaskTest*.
> [FIX-4135][worker]fix sqoop import hive error

- dolphinscheduler-ui/src/js/module/components/crontab/source/_times/day.vue
*Fix The last week of the month for adding/editing timing, preview and save timing will report an error*
```js
this.weekValue = `?`
this.dayValue = val
```
change to
```js
this.weekValue =val
this.dayValue = `?`
```
> [Fix-4054][Api] Cherry from dev to fix The last week of the month for adding/editing timing, preview and save timing will report an error

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/log.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/details/index.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/subdirectory/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/function/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/resource/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/subUdfDirectory/_source/list.vue
- dolphinscheduler-ui/src/js/module/download/index.js
- dolphinscheduler-ui/src/js/module/permissions/index.js
UI Improvement
- *improvement: resovle download url with resolveURL to prevent change of apiPrefix*
- *fix: security page disappear delay problem when force refresh under GENERAL_USER*
- just check new download url, and it's OK
- just force refresh, the problem has been solved.
> [Improvement][UI] download url resolve and security page disappear delay problem under GENERAL_USER

- dolphinscheduler-dist/release-docs/LICENSE
- dolphinscheduler-dist/release-docs/licenses/LICENSE-HikariCP-java6.txt
- dolphinscheduler-dist/release-docs/licenses/LICENSE-c3p0.txt
- dolphinscheduler-dist/release-docs/licenses/LICENSE-mchange-commons-java.txt
- pom.xml
- tools/dependencies/known-dependencies.txt
[4144](https://github.com/apache/incubator-dolphinscheduler/issues/4144)
There is a vulnerability in jackson-databind 2.9.8 ,upgrade recommended
Modify the corresponding jar version in the incubator-dolphinscheduler/pom.xml.
Modify the version of the corresponding jar in tools/dependencies/known-dependencies.txt.
Modify the relevant jar version in the dolphinscheduler-dist/release-docs/LICENSE file.
> [Fix-4144][jar upgrade]upgrade jackson version to 2.9.10

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/shell/AbstractShell.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/LoggerUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/OSUtilsTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/log/TaskLogFilter.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
*Init task logger before init TaskExecuteThread and pass the `taskLogger` in to TaskExecuteThread init method as parameter, so we can record the user and work dir creating log to task instance log, and user can read this log in front-end WebUI.* #3014 
*Use common ShellExecutor in FileUtils.* #2925 
- *Add `taskLogger` parameter  to TaskExecuteThread.* 
- *Add three log utils to LoggerUtils.*
- *Init task logger before create initing TaskExecuteThread, and init task logger process to TaskExecuteProcessor.*
- *Log all detail when create user and working dir in FileUtils.*
> [Feature-2925][server] Cherry pick from dev to init TaskLogger in TaskExecuteProcessor

- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
[FIX-#4184][server-api] load TaskInstanceslow 
page of [TaskInstance] load data by interface "/dolphinscheduler/projects/stressTes/task-instance/list-paging" slow when the size of result more than 230000.
change "join" to " join left " in sql
> [FIX-#4184][server-api] load TaskInstance slow 

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseService.java
When the message of successful execution arrives earlier than
the message of ack,
the message of ack will be discarded,
resulting in some information missing
see #4097
> [FIX-PR-4097][server-master]task ack miss

- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
fix #4190 : When the amount of json data is large, the process list page display slowly.
> [FIX-4190][DAO] When the amount of json data is large, the process list page display slowly.

- dolphinscheduler-api/src/main/resources/application-api.properties
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/flink/FlinkTask.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtilsTest.java
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
- pom.xml
*Fix flink args build problem* #3457 
this closes #3987 #3457 
The official flink run command is `flink run [OPTIONS] <jar-file> <arguments>` (ref: [flink-1.9-cli](https://ci.apache.org/projects/flink/flink-docs-release-1.9/ops/cli.html) and  [flink-1.11-cli](https://ci.apache.org/projects/flink/flink-docs-release-1.11/ops/cli.html)), but there are some errors in the code:
- the `other args` is after the `main args`, so that it will be part of the `<arguments>`
- the flink queue option is also after the `main args`, so that the option doesn't work
- the flink queue option is `-yqu`, not `--qu`, and it's only for …
> [Fix-3457][flink] fix flink args build problem

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/entity/TaskExecutionContext.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/cache/TaskExecutionContextCacheManager.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/cache/impl/TaskExecutionContextCacheManagerImpl.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/cache/TaskExecutionContextCacheManagerTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/processor/TaskCallbackServiceTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessorTest.java
- pom.xml
[FIX-#4172][server-worker] kill task NPE
The cache task will be sent when the Process is generated. Before that, if a kill task appears, then NPE will appear
Modification method: write into the cache when the task is received, and mark it as preData
If the task is killed before the Process is generated, delete the cache directly at this time
It will be judged before the process is generated. If the task has been killed, it will not be executed.
After the new process is created, write it into the cache, and judge again, if kill, then kill the process.
this closes #4172
> [FIX-#4172][server-worker] kill task NPE

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java
this closes #4271 
- *Check whether `filePath` exists in logger server*
*(example:)*
> [Fix-4271][server] Fix IOException or NoSuchFileException in logger server

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
this closes #4264 
fix  the version information deletion function  of DAG diagram interface of workflow definition is not available
Add mVersionDeleteProcessDefinitionVersion method in the dag.vue file
> [fix-4264][UI]The deletion function of version information in DAG diagram cannot work normally

- dolphinscheduler-alert-plugin/dolphinscheduler-alert-dingtalk/pom.xml
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/pom.xml
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/pom.xml
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-script/pom.xml
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-wechat/pom.xml
- dolphinscheduler-dist/pom.xml
- dolphinscheduler-dist/src/main/provisio/dolphinscheduler.xml
- pom.xml
Update maven build, put the alert plugins in the ${install_dir}/lib/plugin/alert/${plugin_module_name} directory
(assembly build and rpm build).
Note: When adding a new plug-in, it must be reflected in provisio/dolphinscheduler.xml.
this closes  #3252
> [Feature-#3252][build]plugins need put in plugins dir when install

- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AccessTokenMapper.xml
this closes #4301 
fix the token management list does not display the user name
add user_name in select sql 
> [fix-4301][dao] The token management list does not display the user name

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/list.vue
this closes #4291 
fix user management authorization operation exceptions do not prompt exception information 
add  .catch(e => {
this.$message.error(e.msg || '')
})
> [fix-4291][UI] user management authorization operation exceptions do not prompt exception information 

- script/dolphinscheduler-daemon.sh
Add startup parameters to daemon
Add $DOLPHINSCHEDULE_OPTS to daemon startup arguments
> [Improvement] Use environment variable $DOLPHINSCHEDULE_OPTS as daemon startup arguments

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
Fixed the problem of judging only 2 nodes in yarnhdips
this closes #4314 
Modify getAcitveRMName in org\apache\dolphinscheduler\common\utils\HadoopUtils.java
> [Fix][common] only two yarns can be selected(#4314)

- dolphinscheduler-ui/.babelrc
- dolphinscheduler-ui/build/config.js
- dolphinscheduler-ui/package.json
- dolphinscheduler-ui/src/js/conf/home/index.js
- dolphinscheduler-ui/src/js/conf/login/index.js
Fix IE 9-11 not supported
This closes #4335
- *Add babel-polyfill*
*(example:)*
**After fix**:
> [Fix-4335][UI] Fix IE 9-11 not supported

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
Modify the status class in the dolphinscheduler-api module, Chinese prompt error.
this close #4178
> [FIX-#4178][api] Start the workflow, the prompt is incorrect 

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/timing/_source/list.vue
this closes #4359 
fix the page does not refresh after clicking the delete function.
add _getScheduleList(false) search result
> [fix-4359][UI]fix the page does not refresh after clicking the delete function.

- dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/list.vue
Add description field to data source list. resolve the issue [#4326](https://github.com/apache/incubator-dolphinscheduler/issues/4326)
this close #4362 
modify dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/list.vue
ui improvement. check datasource  page ui：
- *cd  dolphinscheduler-ui*
- *run "npm run start"*
- *go to "http://localhost:8888/#/datasource/list"*
> [Improvement-4326][ui] Add description field to data source list

- DISCLAIMER
- dolphinscheduler-ui/src/js/conf/home/App.vue
- dolphinscheduler-ui/src/js/conf/home/router/index.js
Fix data loss in switched tab
This closes #4293
- *Add `refesh_in_switched_tab` in router meta*
- *Set `refesh_in_switched_tab: true` in detail and list page which needs to refresh*
*(example:)*
> [Fix-4293][UI] Fix data loss in switched tab

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/shell/ShellExecutor.java
- Fix: kill task error because of shell output truncation （由于shell 输出截断，导致kill任务失败)
- This closes #4455 
- In the common module, fix the problem of truncation exceeding buf when the shell script is executed to obtain the output, and only the last time is retained
- common 模块中，修复执行 shell 脚本获取输出时超过buf的截断，仅保留最后一次的问题
- *The local production environment verified*
> [Fix-4455][common] fix parse shell output

- .github/workflows/ci_backend.yml
- .github/workflows/ci_e2e.yml
- .github/workflows/ci_frontend.yml
- .github/workflows/ci_ut.yml
- .licenserc.yaml
- dolphinscheduler-ui/src/js/module/visibility/index.js
- pom.xml
This PR sets up license-eye to check the license headers, and add review comments when there are files missing license header.
`.github/workflows/*.yml`:
- Set up license-eye to check license headers.
- Use built-in feature to checkout submodules instead of manually checking out.
> chore: set up license-eye to check license headers

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
- dolphinscheduler-ui/src/js/conf/home/store/dag/actions.js
- dolphinscheduler-ui/src/js/conf/home/store/dag/mutations.js
- dolphinscheduler-ui/src/js/conf/home/store/dag/state.js
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Implement UI #4463 
this close #4463 
- Add variable 'releaseState', which indicates whether to go online or not. 0 means not to go online, 1 means online, online by default
- Add a checkbox option and show it when saving the workflow definition in detail page
- Add 'releaseState' param in 'updateDefinition' action method
> [Feature-4463][UI]: Add an option to the UI page for saving the workflow definition: whether to go online?

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HiveConfUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/HiveConfUtilsTest.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/HiveDataSource.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/datasource/HiveDataSourceTest.java
- pom.xml
this PR closes #4472
Solve the problem of parameter splicing of permission part in Hive JDBC URL, such as parameter: tez.queue.name=tqn The spliced JDBC URL is jdbc:hive2://:,:/dbName;tez.queue.name=tqn, and the normal JDBC URL is jdbc:hive2://:,:/dbName?tez.queue.name=tqn
update HiveDataSource.filterOther()
- HiveConfUtilsTest
- HiveDataSourceTest
> [fix-4472][DataSource] Hive JDBC partial permission parameter concatenation JDBC URL error

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
Before pre-compiling sql, replace the custom parameters marked with !{}
to prevent the parameters in the hive plus partition path from being
replaced with single quotes
Closes This closes #4496
- Add a method to replace custom parameters before pre-compiled SQL
- 增加一个方法在预编译sql之前替换自定义参数
> [feat-4496][server]  Add to! {} is used to mark the custom parameters to be output as-is in sql

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
- dolphinscheduler-dist/release-docs/LICENSE
- pom.xml
- tools/dependencies/known-dependencies.txt
Recommended upgrade version：2.10.5.1 from 2.9.10
----------------------------------------------------
jackson-annotations-2.10.5.jar
jackson-core-2.10.5.jar
jackson-databind-2.10.5.jar
jackson-datatype-jdk8-2.9.10.jar
jackson-datatype-jsr310-2.9.10.jar
jackson-module-parameter-names-2.9.10.jar
> [Improvement-#4503][dolphinscheduler-dist]Jackson version upgraded to 2.10.5 from 2.9.10

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectServiceTest.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapperTest.java
Optimize the api *ProjectService.queryAllProjectList*.
It's not good to query all processDefinition list and pick the project ids in menmory.
ProjectServiceImpl.java
- Changed methord `queryAllProjectList`
ProjectServiceTest.java
- Changed methord `testQueryAllProjectList`
ProcessDefinitionMapper.java
- Added method `listProjectIds`
ProcessDefinitionMapper.xml
- Added sql for `listProjectIds` mapper
ProcessDefinitionMapperTest.java
- Added method `listProjectIds`
This pull request is already covered by existing tests:
- *ProjectServiceTest.testQueryAllProjectList*
- *ProcessDefinitionMapperTest.listProjectIds*
> [Improvement][API] ProjectService queryAllProjectList API optimization

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/store/dag/state.js
this PR closes #4493 
The Process Definition interface parameter releaseState is changed to an enumeration type 
- ProcessDefinitionController.java 
- ProcessDefinitionService.java
- udp.vue
- list.vue
> [Improvement-4493][api] The Process Definition interface parameter releaseState is changed to an enumeration type 

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
this PR closes #4544 
fix process-instance delete button display condition,When the status is success or failure or stop or pause, the page displays the delete button.
update delete button disabled value in the instance/pages/list/_source/list.vue
> [Fix-4544][UI] process-instance delete button display condition error

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/runner/AlertSender.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertPluginInstanceServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AlertPluginInstanceServiceTest.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/AlertPluginInstance.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AlertGroupMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertGroupMapper.xml
- pom.xml
* Fix mybatis-plus empty value update problem
* When deleting the alert-plugin instance, determine whether there is an alert group association
* When the alert is executed, if the alarm group is not bound to the alert plug-in, the alert status is updated to fail.
> [Improvement][Alert]Alert problem repair and optimization

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/improvement_suggestion.md
- .github/ISSUE_TEMPLATE/question.md
The issue label should be handed over to people who are familiar with the project to mark. Currently, the label is automatically marked, and the application effect is not ideal.
A good application of the issue tag can help us save a lot of energy, so I recommend removing the automatic tag.
> [github][issue-template]remove issue label

- dolphinscheduler-server/src/main/resources/logback-master.xml
- dolphinscheduler-server/src/main/resources/logback-worker.xml
this PR closes #4566 
worker-server logback partial logs are not printed.
- remove log filter to logback-worker.xml
> [Fix-4566][worker] worker-server logback partial logs are not printed

- dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/MailParamsConstants.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/MailUtilsTest.java
this PR closes #4641 
fix Alert-server email alert error, the message is 'Sending the email to the following server failed :null:null'
> [Fix-4641][Alert] Sending the email to the following server failed :null:null

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
this PR closes #4568 
When the workflow definition name validation API fails, the system prompts that the workflow definition name already exists,
the system normally prompts workflow definition name validation error
> [Improvement-4568][API] When the workflow definition name validation API fails, the system prompts that the workflow definition name already exists

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/interceptor/LocaleChangeInterceptor.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/BaseService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SessionServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/BaseServiceTest.java
*Use WebUtils.getCookie instead of BaseService.getCookie*
- *Use WebUtils.getCookie instead of BaseService.getCookie*
*(example:)*
> [Improvement][Api] Use WebUtils.getCookie instead of BaseService.getCookie

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtils.java
Fix flink `-yn` option missing after upgrading
> [1.3.5-prepare][Fix][Flink] Fix flink -yn option missing after upgrading

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/UDFUtils.java
*Fix udf jar path not exist when fs.defaultFS starts with file:///*
This closes #4691
- *Modify dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/UDFUtils.java*
> [Fix][UDF] Fix udf jar path not exist when fs.defaultFS starts with file:///
