- docs/zh_CN/后端部署文档.md
- escheduler-server/src/test/java/cn/escheduler/server/zk/ZKWorkerClientTest.java
> update backend deployment doc

- escheduler-alert/src/main/java/cn/escheduler/alert/utils/Constants.java
- escheduler-alert/src/main/java/cn/escheduler/alert/utils/MailUtils.java
- escheduler-common/pom.xml
- escheduler-server/src/main/java/cn/escheduler/server/worker/runner/FetchTaskThread.java
1，Outlook TLS support
2，Worker performs the creation of a tenant if the tenant does not exist
3，Protobuf conflict resolution
4，Servlet conflict resolution
> 190404 improve commit

- README.md
- docs/zh_CN/后端部署文档.md
- escheduler-api/src/main/java/cn/escheduler/api/controller/ProcessDefinitionController.java
- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessDefinitionService.java
- escheduler-dao/src/main/java/cn/escheduler/dao/ProcessDao.java
- escheduler-server/src/main/java/cn/escheduler/server/zk/ZKMasterClient.java
fix bug spelling error in process dao
> fix bug spelling error in process dao

- README.md
add address for having a taste in README.md
> Dev add address for having a taste

- escheduler-alert/src/main/java/cn/escheduler/alert/utils/MailUtils.java
to avoid exception javax.mail.SendFailedException: No recipient
addresses. Especially from SQL Task
>  before send mail, check whether no receivers && cc receivers

- docs/zh_CN/后端部署文档.md
> update install document

- escheduler-common/src/main/java/cn/escheduler/common/Constants.java
- escheduler-common/src/main/java/cn/escheduler/common/utils/CommonUtils.java
- escheduler-common/src/main/resources/common/common.properties
- escheduler-server/src/main/java/cn/escheduler/server/worker/task/PythonCommandExecutor.java
- escheduler-server/src/main/java/cn/escheduler/server/worker/task/python/PythonTask.java
Python task specifies path execution update
> Branch 1.0.0

- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessDefinitionService.java
> fix graphHasCycle

- Dockerfile
- conf/zoo.cfg
> add dockerfile

- escheduler-api/src/main/java/cn/escheduler/api/enums/Status.java
- escheduler-api/src/main/java/cn/escheduler/api/service/UsersService.java
TENANT_NAME_EXIST 这里实际验证的是租户编码，不是租户名称是否唯一。
> TENANT_NAME_EXIST 这里实际验证的是租户编码，不是租户名称是否唯一。

- docs/zh_CN/后端部署文档.md
update create and upgrade introduce
> update create and upgrade introduce

- escheduler-dao/src/main/java/cn/escheduler/dao/datasource/ConnectionFactory.java
> remove development filters

- sql/upgrade/1.0.2_schema/mysql/escheduler_ddl.sql
add worker_group_id in t_escheduler_process_instance
> add ac_escheduler_T_t_escheduler_process_instance_C_worker_group_id

- escheduler-api/src/main/java/cn/escheduler/api/controller/ProcessDefinitionController.java
- escheduler-api/src/main/java/cn/escheduler/api/enums/Status.java
- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessDefinitionService.java
- escheduler-api/src/test/java/cn/escheduler/api/service/ProcessDefinitionServiceTest.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/ScheduleMapper.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/ScheduleMapperProvider.java
add delete process definition by id
> add delete process definition by id

- escheduler-api/src/main/java/cn/escheduler/api/controller/SchedulerController.java
- escheduler-api/src/main/java/cn/escheduler/api/enums/Status.java
- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessDefinitionService.java
- escheduler-api/src/main/java/cn/escheduler/api/service/SchedulerService.java
- escheduler-api/src/main/java/cn/escheduler/api/service/TenantService.java
- escheduler-common/src/main/java/cn/escheduler/common/utils/HadoopUtils.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/ScheduleMapper.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/ScheduleMapperProvider.java
add listFileStatus and update deleteTenantById
> add listFileStatus and update deleteTenantById

- escheduler-api/src/main/java/cn/escheduler/api/controller/ProcessDefinitionController.java
- escheduler-api/src/main/java/cn/escheduler/api/controller/ProcessInstanceController.java
- escheduler-api/src/main/java/cn/escheduler/api/enums/Status.java
- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessDefinitionService.java
- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessInstanceService.java
- escheduler-api/src/test/java/cn/escheduler/api/service/ProcessDefinitionServiceTest.java
- escheduler-api/src/test/java/cn/escheduler/api/service/ProcessInstanceServiceTest.java
support batch delete process definition and process instance
> support batch delete process definition and process instance

- escheduler-common/src/main/java/cn/escheduler/common/task/sql/SqlParameters.java
- escheduler-server/src/main/java/cn/escheduler/server/worker/task/sql/SqlTask.java
Support for custom SQL job title
> Support for custom SQL job title

- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessDefinitionService.java
add determine if the login user is the owner of the process definition or schedule
> add determine if the login user is the owner of the process definition or schedule

- escheduler-alert/src/main/java/cn/escheduler/alert/utils/Constants.java
- escheduler-alert/src/main/java/cn/escheduler/alert/utils/MailUtils.java
- escheduler-alert/src/main/resources/alert.properties
对启用了SSL的邮箱支持，在阿里云企业邮箱、163上测试OK
> 启用SSL的邮箱发送邮件

- escheduler-dao/src/main/java/cn/escheduler/dao/ProcessDao.java
add tolerance tasks when start failure task
>  add tolerance tasks when start failure task

- escheduler-api/src/main/java/cn/escheduler/api/service/ExecutorService.java
remove checking definition state when stop/pause.
> remove checking definition state when stop/pause.

- docs/zh_CN/后端部署文档.md
add monitorServerState in 1.0.3
> add monitorServerState in 1.0.3

- escheduler-common/src/main/java/cn/escheduler/common/queue/TaskQueueZkImpl.java
Determine if a node exists before deleting it
> Determine if a node exists before deleting it

- escheduler-common/src/main/java/cn/escheduler/common/utils/DependentUtils.java
- escheduler-common/src/main/java/cn/escheduler/common/utils/dependent/DependentDateUtils.java
- escheduler-common/src/test/java/cn/escheduler/common/utils/DependentUtilsTest.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/ProcessInstanceMapperProvider.java
- escheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/commcon.js
- escheduler-ui/src/js/module/i18n/locale/en_US.js
- escheduler-ui/src/js/module/i18n/locale/zh_CN.js
> add today for dependent item

- install.sh
Two lines join to form one line
> Two lines join to form one line

- escheduler-server/src/main/java/cn/escheduler/server/worker/task/sql/SqlTask.java
update getSqlAndSqlParamsMap in order to replace title
> update getSqlAndSqlParamsMap in order to replace title

- docs/zh_CN/README.md
- docs/zh_CN/快速上手.md
>  update 1.0.3 documents

- escheduler-api/src/main/java/cn/escheduler/api/service/ResourcesService.java
if hdfs path is not exists return result
> if hdfs path is not exists return result

- escheduler-api/src/main/java/cn/escheduler/api/dto/resources/ResourceTreeBuilder.java
- escheduler-api/src/main/java/cn/escheduler/api/dto/resources/ResourceViewDto.java
- escheduler-api/src/test/java/cn/escheduler/api/dto/resources/ResourceTreeBuilderTest.java
- escheduler-api/src/test/java/cn/escheduler/api/dto/resources/ResourceViewDtoTest.java
- escheduler-common/src/main/java/cn/escheduler/common/enums/ResourceType.java
- escheduler-dao/src/main/java/cn/escheduler/dao/model/Resource.java
add resource tree utils and model in order to create resource tree
> Dev 1.1.0 resources

- escheduler-api/src/main/java/cn/escheduler/api/service/TenantService.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/ProcessDefinitionMapperProvider.java
1.Added checks on whether HDFS is configured to be true in delete tenant
2.Added the ability to sort by timing status
> Branch 1.0.2

- escheduler-api/src/test/java/cn/escheduler/api/controller/ResourcesControllerTest.java
> add verifyResourceName test

- escheduler-api/src/main/java/cn/escheduler/api/enums/Status.java
- escheduler-api/src/main/java/cn/escheduler/api/service/ResourcesService.java
determine if the file exists in hdfs when read file
> determine if the file exists in hdfs when read file

- escheduler-api/src/main/java/cn/escheduler/api/service/DataSourceService.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/DataSourceMapper.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/DataSourceMapperProvider.java
Added the ability for administrators to view all data sources
> Added the ability for administrators to view all data sources

- escheduler-api/src/main/java/cn/escheduler/api/service/DataSourceService.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/DataSourceMapper.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/DataSourceMapperProvider.java
update the ability for administrators to view all data sources by type
> update the ability for administrators to view all data sources by type

- escheduler-alert/pom.xml
remove httpcore and httpclient
> remove httpcore and httpclient

- install.sh
> add Enterprise WeChat config

- escheduler-alert/src/test/java/cn/escheduler/alert/utils/EnterpriseWeChatUtilsTest.java
read Enterprise WeChat config test
> read Enterprise WeChat config test

- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessInstanceService.java
- escheduler-common/src/main/java/cn/escheduler/common/queue/TaskQueueZkImpl.java
- escheduler-dao/src/main/java/cn/escheduler/dao/ProcessDao.java
- escheduler-server/src/main/java/cn/escheduler/server/worker/runner/FetchTaskThread.java
fix sub process worker group id is 0
update worker get task from queue
>  update worker get task from queue

- sql/upgrade/1.1.0_schema/mysql/escheduler_dml.sql
The version will be updated automatically, so there is no need to add
> The version will be updated automatically, so there is no need to add

- escheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/timing.vue
remove resolve because resolve is not defined
> remove resolve because resolve is not defined

- escheduler-api/src/main/java/cn/escheduler/api/service/DataSourceService.java
- escheduler-common/src/main/java/cn/escheduler/common/Constants.java
optimize datasource connection params safety
>  optimize datasource connection params safety

- escheduler-api/src/main/java/cn/escheduler/api/controller/MonitorController.java
- escheduler-api/src/main/java/cn/escheduler/api/service/MonitorService.java
- escheduler-api/src/main/java/cn/escheduler/api/utils/ZookeeperMonitor.java
- escheduler-api/src/test/java/cn/escheduler/api/utils/ZookeeperMonitorUtilsTest.java
- escheduler-common/src/main/java/cn/escheduler/common/queue/TaskQueueZkImpl.java
- escheduler-common/src/main/java/cn/escheduler/common/utils/IpUtils.java
- escheduler-common/src/main/java/cn/escheduler/common/zk/AbstractZKClient.java
- escheduler-common/src/test/java/cn/escheduler/common/queue/TaskQueueImplTest.java
- escheduler-common/src/test/java/cn/escheduler/common/utils/IpUtilsTest.java
- escheduler-server/src/main/java/cn/escheduler/server/ResInfo.java
- escheduler-server/src/main/java/cn/escheduler/server/zk/ZKMasterClient.java
- escheduler-server/src/main/java/cn/escheduler/server/zk/ZKWorkerClient.java
- escheduler-server/src/test/java/cn/escheduler/server/zk/ZKWorkerClientTest.java
> get master/worker informations from zookeeper

- escheduler-common/src/main/java/cn/escheduler/common/Constants.java
> update email regex

- escheduler-dao/src/main/java/cn/escheduler/dao/upgrade/shell/CreateEscheduler.java
- escheduler-dao/src/main/java/cn/escheduler/dao/upgrade/shell/UpgradeEscheduler.java
update upgrade and create log tips
> update upgrade and create log tips

- escheduler-server/src/main/java/cn/escheduler/server/utils/LoggerUtils.java
fix bug that the task instance of MR cannot stop in some cases. #516
> fix bugs #516

- escheduler-api/src/main/java/cn/escheduler/api/enums/Status.java
- escheduler-api/src/main/java/cn/escheduler/api/service/ExecutorService.java
- escheduler-common/src/main/java/cn/escheduler/common/queue/TaskQueueZkImpl.java
- escheduler-server/src/main/java/cn/escheduler/server/worker/runner/FetchTaskThread.java
check tenant exists when running a process
update poll task
> check tenant exists when running a process

- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessDefinitionService.java
- escheduler-api/src/main/java/cn/escheduler/api/service/SchedulerService.java
fix bug 569 to resolve schedule doesn't really stop
> fix bug 569 to resolve schedule doesn't really stop

- escheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
- escheduler-ui/src/js/module/i18n/locale/en_US.js
- escheduler-ui/src/js/module/i18n/locale/zh_CN.js
>  update i18n

- escheduler-server/src/main/java/cn/escheduler/server/worker/task/AbstractCommandExecutor.java
fix 594 to resolve The task timeout need deletes the child process
> The task timeout need deletes the child process

- escheduler-dao/src/main/resources/dao/data_source.properties
reset datasource default setting
> change datasource default setting

- escheduler-common/src/main/java/cn/escheduler/common/queue/TaskQueueZkImpl.java
> double check 变量需要volatile修饰

- escheduler-common/src/test/java/cn/escheduler/common/utils/CollectionUtilsTest.java
I've analysed your codebase and noticed that `cn.escheduler.common.utils.CollectionUtils` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.
> Add unit tests for cn.escheduler.common.utils.CollectionUtils

- escheduler-api/src/main/java/cn/escheduler/api/service/MonitorService.java
- escheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
- escheduler-ui/src/js/module/i18n/locale/en_US.js
- escheduler-ui/src/js/module/i18n/locale/zh_CN.js
> update i18n, delete zk links 

- escheduler-api/src/main/java/cn/escheduler/api/enums/Status.java
- escheduler-server/src/main/java/cn/escheduler/server/zk/ZKMasterClient.java
fix bug. task instance not set host(#625)
> fix bug. task instance not set host(#625)(#525)

- escheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
fix bug.The cellphone is not supported for 199 telecom segment when create a user (#641)
> fix bug #641

- escheduler-common/src/main/java/cn/escheduler/common/Constants.java
Add support for underline in mailbox format
> Add support for underline in mailbox format

- README.md
- docs/zh_CN/SUMMARY.md
- escheduler-api/src/main/java/cn/escheduler/api/controller/MonitorController.java
- escheduler-api/src/main/java/cn/escheduler/api/service/MonitorService.java
- escheduler-api/src/main/java/cn/escheduler/api/service/SchedulerService.java
- escheduler-api/src/main/java/cn/escheduler/api/service/ServerService.java
- escheduler-api/src/main/java/cn/escheduler/api/utils/ZookeeperMonitor.java
- escheduler-api/src/test/java/cn/escheduler/api/utils/ZookeeperMonitorUtilsTest.java
- escheduler-common/src/main/java/cn/escheduler/common/model/MasterServer.java
- escheduler-common/src/main/java/cn/escheduler/common/utils/ResInfo.java
- escheduler-common/src/main/java/cn/escheduler/common/zk/AbstractZKClient.java
- escheduler-dao/src/main/java/cn/escheduler/dao/ServerDao.java
- escheduler-dao/src/main/java/cn/escheduler/dao/mapper/MasterServerMapper.java
- escheduler-dao/src/test/java/cn/escheduler/dao/mapper/MasterServerMapperTest.java
- escheduler-server/src/main/java/cn/escheduler/server/master/MasterServer.java
- escheduler-server/src/main/java/cn/escheduler/server/master/runner/MasterSchedulerThread.java
- escheduler-server/src/main/java/cn/escheduler/server/worker/runner/FetchTaskThread.java
- escheduler-server/src/main/java/cn/escheduler/server/zk/ZKMasterClient.java
- escheduler-server/src/main/java/cn/escheduler/server/zk/ZKWorkerClient.java
refactor zkMasterClient/zkWorkerClient
fix bug: close zk links
> refactor zkMasterClient/zkWorkerClient

- escheduler-common/src/main/java/cn/escheduler/common/Constants.java
- escheduler-common/src/main/java/cn/escheduler/common/task/sql/LoggableStatement.java
- escheduler-server/src/main/java/cn/escheduler/server/worker/task/sql/SqlTask.java
fix bug.HivePreparedStatement can't print the actual SQL executed (#667)
> fix bug.HivePreparedStatement can't print the actual SQL executed (#667)

- docs/en_us/1.0.1-release.md
- docs/en_us/1.0.2-release.md
- docs/en_us/1.0.3-release.md
- docs/en_us/1.1.0-release.md
- docs/en_us/Backend Deployment Document.md
- docs/en_us/Backend development documentation.md
- docs/en_us/EasyScheduler-FAQ.md
- docs/en_us/Frontend Deployment Document.md
- docs/en_us/Frontend development documentation.md
- docs/en_us/Quick Start.md
- docs/en_us/System manual.md
- docs/en_us/Upgrade documentation.md
> add en-us documents

- docs/en_US/EasyScheduler Proposal.md
> use Jenkins

- escheduler-common/pom.xml
- escheduler-common/src/main/java/cn/escheduler/common/job/db/HiveDataSource.java
- pom.xml
1.Remove useless dependencies
2.Add jsp-2.1-6.1.14 dependence
> Remove useless dependencies and add jsp-2.1-6.1.14

- pom.xml
add embedded h2 db
add jacoco report plugin for jenkins
> add embedded h2 db and jacoco report plugin for jenkins

- escheduler-api/src/main/java/cn/escheduler/api/service/SessionService.java
- escheduler-dao/src/test/java/cn/escheduler/dao/mapper/AccessTokenMapperTest.java
- escheduler-dao/src/test/java/cn/escheduler/dao/mapper/AlertGroupMapperTest.java
- escheduler-dao/src/test/java/cn/escheduler/dao/mapper/AlertMapperTest.java
- escheduler-dao/src/test/java/cn/escheduler/dao/mapper/DataSourceMapperTest.java
>  add unit test

- escheduler-api/src/main/java/cn/escheduler/api/controller/ExecutorController.java
FIX bug
[BUG] ExecutorController.java 92行logger.info日志输出缺少参数 #734
> fix bug #734

- escheduler-common/src/main/java/cn/escheduler/common/task/sql/LoggableStatement.java
- escheduler-common/src/main/java/cn/escheduler/common/task/sql/SqlBinds.java
- escheduler-server/src/main/java/cn/escheduler/server/utils/SqlTaskUtils.java
- escheduler-server/src/main/java/cn/escheduler/server/worker/task/sql/SqlTask.java
- escheduler-server/src/test/java/cn/escheduler/server/utils/SqlTaskUtilsTest.java
fix bug #738 to print the actual SQL statement executed
> fix bug #738 to print the actual SQL statement executed

- escheduler-server/src/main/java/cn/escheduler/server/master/AbstractServer.java
> add AbstractServer.java

- pom.xml
Trivial refactor to move hardcoded dependency versions to parent pom properties section.
> Refactor hardcoded versions in parent pom

- escheduler-ui/package.json
- escheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
- escheduler-ui/src/lib/@analysys/ans-ui/package.json
- escheduler-ui/src/lib/@fedor/io/package.json
1.Modify the status of workflow instance page to run time, forbid clicking delete button；
2.Delete package page ‘jasmine-core,babel-runtime,karma’
> instance/pages/list/_source/list.vue && package

- escheduler-dao/src/main/java/cn/escheduler/dao/ProcessDao.java
- escheduler-server/src/main/java/cn/escheduler/server/worker/runner/FetchTaskThread.java
user-specified queue takes precedence over tenant queue
> bugfix-user-specified queue takes precedence over tenant queue

- docs/en_US/architecture-design.md
- docs/zh_CN/系统使用手册.md
- docs/zh_CN/系统架构设计.md
modify some md files that can't display the images normally
----------
更新无法正常显示图片的markdown文档
> update markdown docs which can not display images normally

- escheduler-alert/src/main/java/cn/escheduler/alert/AlertServer.java
- escheduler-common/src/main/java/cn/escheduler/common/thread/ThreadPoolExecutors.java
> Fix singleton with volatile

- README.md
> Highlight the mail list as high priority contact channel.

- pom.xml
update fastjson version，the lower version has a security bug.
> [fix bug][#847] Update pom.xml

- escheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/dependItemList.vue
- escheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/dependent.vue
- escheduler-ui/src/js/conf/home/pages/dag/definitionDetails.vue
- escheduler-ui/src/js/conf/home/pages/dag/index.vue
- escheduler-ui/src/js/conf/home/pages/dag/instanceDetails.vue
repair cross-project dependency delete bug
(修复跨项目流依赖删除异常)
> [BUG][#857]repair cross-project dependency delete bug

- escheduler-dao/src/main/java/cn/escheduler/dao/ProcessDao.java
Fix issue #885 
https://github.com/apache/incubator-dolphinscheduler/issues/885
> #885 Fix comment error in taskZkInfo function

- escheduler-ui/src/js/module/i18n/locale/zh_CN.js
update zh_CN.js delete Content repetition . 'Complement range': '补数范围'
> [BUG][#877]update zh_CN.js delete Content repetition

- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessDefinitionService.java
repair the imported workflow timer is online and ineffective
（修复导入工作流定时器状态为上线不起效果的问题）
> [BUG][#888]repair the imported workflow timer is online and ineffective

- escheduler-api/src/main/java/cn/escheduler/api/service/ProcessDefinitionService.java
Fixed duplicate name of import and export workflow and adapted Dependent component
(修复导入导出工作流重复名称和适配Dependent组件)
> [BUG][#896]Fixed duplicate name of import and export workflow and adapted Dependent component

- escheduler-alert/src/main/java/cn/escheduler/alert/AlertServer.java
- escheduler-api/src/main/java/cn/escheduler/api/CombinedApplicationServer.java
```
AlertServer.getInstance(alertDao)
```
alertDao param solved this
> Fix alert server NullPointerException (#948)

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CollectionUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/AbstractZKClient.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/dependent/DependentTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/http/HttpTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
spotbugs: make map traversal more efficient @Baoqi
> spotbugs: make map traversal more efficient

- .github/workflows/ci.yml
github actions ci compile check
> github actions ci compile check

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/dependItemList.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/dependent.vue
repair cross-project dependency cascading exception
(修复跨项目流依赖级联异常)
> [BUG][#1036]repair cross-project dependency cascading exception(修复跨项目流依赖级联异常)

- pom.xml
Add  3rd.css to the whitelist of license check
> Add  3rd.css to the whitelist of license check 

- .github/workflows/ci.yml
- pom.xml
Fix ci not work for format error in .yml file
> Fix ci not work for format error in .yml file

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtils.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/PropertyUtils.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/TaskNodeRelation.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/PropertyUtils.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/MonitorDBDao.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/TaskRecordDao.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/PropertyUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
spotbugs: bug check and modify
> spotbugs: bug check and modify

- escheduler-common/pom.xml
> [Fix] zookeeper dashboard error(#991)

- dockerfile/Dockerfile
- dockerfile/conf/dolphinscheduler/conf/application.properties
- dockerfile/conf/dolphinscheduler/conf/org/apache/dolphinscheduler/dao/mapper/CommandMapper.xml
- dockerfile/conf/dolphinscheduler/conf/org/apache/dolphinscheduler/dao/mapper/ErrorCommandMapper.xml
- dockerfile/conf/dolphinscheduler/conf/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
- dockerfile/conf/dolphinscheduler/conf/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
- dockerfile/conf/dolphinscheduler/conf/org/apache/dolphinscheduler/dao/mapper/SessionMapper.xml
- dockerfile/conf/dolphinscheduler/conf/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
- dockerfile/conf/dolphinscheduler/conf/org/apache/dolphinscheduler/dao/mapper/UDFUserMapper.xml
- dockerfile/conf/dolphinscheduler/conf/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapper.xml
- dockerfile/conf/dolphinscheduler/conf/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
- dockerfile/conf/dolphinscheduler/conf/quartz.properties
- dockerfile/startup.sh
> dockerfile pg db migration

- pom.xml
> update scm pom.xml

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ExecutionStatus.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/TaskStateType.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/graph/DAG.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/shell/AbstractShell.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/shell/ShellExecutor.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/Bytes.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CollectionUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CommonUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DependentUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/EncryptionUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/IpUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/PropertyUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ResInfo.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/SchemaUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ScriptRunner.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/TaskParametersUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/placeholder/BusinessTimeUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/placeholder/PlaceholderUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/placeholder/PropertyPlaceholderHelper.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/placeholder/TimePlaceholderUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/AbstractZKClient.java
**add java doc for common module**
> add java doc for common module

- .github/workflows/ci_backend.yml
- dolphinscheduler-ui/package.json
- dolphinscheduler-ui/pom.xml
> ci and maven pom.xml modify

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/ConnectionFactory.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/Application.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/SpringApplication.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractYarnTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/dependent/DependentExecute.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/dependent/DependentTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/http/HttpTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/processdure/ProcedureTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/python/PythonTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/shell/ShellTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/shell/ShellCommandExecutorTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/sql/SqlExecutorTest.java
- pom.xml
delete class App, let spring manage connectionFactory
> merge from dev-db

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/CombinedApplicationServer.java
- dolphinscheduler-api/src/main/resources/application-combined.properties
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
- script/dolphinscheduler-daemon.sh
Combined Server don't work well in new dev-db branch , this check in is to make it works again.
> make combined server works in new dev-db branch

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/CombinedApplicationServer.java
Use @Import will cause both Combined Server & ApiServer got the MasterServer/WorkerServer imported.
So, add ConditionalOnProperty to only import for CombinedServer
> conditional Import on CombinedServer to solve APIServer issue

- pom.xml
- style/checkstyle-suppressions.xml
- style/checkstyle.xml
This PR adds Java Checkstyle rules. Improving rules is a step-by-step process. This is the first step.
> [Checkstyle] Add java checkstyle

- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/CollectionUtilsTest.java
> unittest-demo

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/gantt/GanttDto.java
- style/checkstyle.xml
optimize java code checkstyle for EmptyStatement rule
optimize java code checkstyle for EmptyStatement rule
> [checkstyle] optimize java code checkstyle for EmptyStatement rule

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectController.java
- dolphinscheduler-ui/src/js/conf/home/store/dag/actions.js
- dolphinscheduler-ui/src/js/module/components/fileUpdate/definitionUpdate.vue
Changelog category :
* New Feature
Detailed description :
change the camel-case with kebab
> [dolphinscheduler- 1219] [newfeature] Non compliant code

- install.sh
- script/config/install_config.conf
- script/config/run_config.conf
- script/monitor-server.py
- script/scp-hosts.sh
- script/start-all.sh
- script/stop-all.sh
*change log*
- Support custom SSH port
> Add config to override default ssh port for install scripts. #780

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/ServiceModelToSwagger2MapperImpl.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/FourLetterWordMain.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ExecutionStatus.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/AbstractZKClient.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/queue/TaskQueueImplTest.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/TaskRecordDao.java
- style/checkstyle.xml
optimize java code checkstyle for LeftCurly rule
optimize java code checkstyle for LeftCurly rule
> [checkstyle] optimize java code checkstyle for LeftCurly rule

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/DbType.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/DB2ServerDataSource.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/DataSourceFactory.java
- dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/createDataSource.vue
- dolphinscheduler-ui/src/js/conf/home/store/dag/state.js
This pr is for #1345 to add the DB2 Datasource  , now we can use it to connect with DB2 .
The commit dosen't include the DB2 driver in .pom , i am not sure about the driver's license . 
- Add  DB2 case in DataSourceService.java and DataSourceFactory.java .
- Add an new class DB2ServerDataSource.java .
- Define DB2 type in DbType.java and state.js .
- Define the DB2 driver class in Constants.java .
- Add DB2 radio in createDataSource.vue .
- Manually verified the change by testing locally. I have been tested with DB2 11.1 version .
> [dolphinscheduler-1345] [newfeature] Add DB2 Datasource

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/variable/variablesView.vue
- dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/db.vue
- dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/master.vue
- dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/worker.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/email.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/tree/index.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/gantt/index.vue
- dolphinscheduler-ui/src/js/module/components/secondaryMenu/secondaryMenu.vue
- dolphinscheduler-ui/src/js/module/components/transfer/transfer.vue
> "v-for" add key

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/index/_source/taskCtatusCount.vue
- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
- dolphinscheduler-ui/src/js/conf/home/pages/user/pages/password/_source/info.vue
- dolphinscheduler-ui/src/js/module/components/nav/nav.vue
- dolphinscheduler-ui/src/js/module/components/secondaryMenu/secondaryMenu.vue
- dolphinscheduler-ui/src/js/module/components/transfer/resource.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
> Password verification and v-for add key

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/localParams.vue
For #1437.
change maxlength from 128 to 256.
- *Edit localParams.vue*
> change maxlength from 128 to 256

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterSchedulerThread.java
fix the #1442 
comment correct
This change is a trivial comment correct without any test coverage.
> fix comment error

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/OSUtilsTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/FetchTaskThread.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/ProcessUtilsTest.java
- compatible with pstree command
- compatible with create user command
- compatible with list user command
*In the current version, certain Linux commands do not exist or the command execution behavior is inconsistent under the Mac system, which causes the Mac system to fail to debug and develop.*
- *Add getUserListFromMac function to OSUtils.java*
- *Add createMacUser function to OSUtils.java*
- *Add OSUtilsTest.java file*
- *Modify getPidsStr on ProcessUtils.java*
- *Add ProcessUtilsTest.java file*
- *Added OSUtilsTest.getUserList to verify the change.*
- *Added ProcessUtilsTest.getPidsStr to verify the change.*
- *Manually verified the change by testing locally on mac and centos systems
.*
> Support Mac local development and debugging

- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/graph/DAGTest.java
- pom.xml
> unit test common graph

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/CheckUtils.java
For #1480.
The method checkEmail does not have a null check.
When the email is empty, it will be a null point exception.
So I fix it with a null check.
- *CheckUtils.java*
- *Added CheckUtilsTest to verify the change.*
> Add null check in method checkEmail

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/CheckUtils.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/CheckUtilsTest.java
- pom.xml
For #1465.
Add the unit test of CheckUtils.
- *Add CheckUtilsTest.java*
- *Added CheckUtilsTest to verify the change.*
> Add CheckUtilsTest.java , The unit test for CheckUtils

- sql/dolphinscheduler-postgre.sql
- sql/dolphinscheduler_mysql.sql
- sql/upgrade/1.0.1_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.1.0_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.2.0_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.2.0_schema/postgresql/dolphinscheduler_ddl.sql
- sql/upgrade/1.2.0_schema/postgresql/dolphinscheduler_dml.sql
*add license in sql files*
*add license in sql files*
> add license in sql files

- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/FileUtilsTest.java
- pom.xml
For #1465.
Add FileUtilsTest.java , the unit test for FileUtils.
- Add /api/utils/FileUtilsTest.java to root pom.xml
- Add FileUtilsTest.java
- *Added FileUtilsTest to verify the change.*
> Add FileUtilsTest.java , the unit test for FileUtils

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/FuncUtils.java
- dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/FuncUtilsTest.java
- dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/JSONUtilsTest.java
- pom.xml
For #1465.
1.Add FuncUtilsTest.java and JSONUtilsTest.java.
2.Add null check in FuncUtils.mkString.
3.Add ut config in pom.
- *Add FuncUtilsTest.java*
- *Add JSONUtilsTest.java*
- *Edit FuncUtils.java*
- *Add ut include path to root pom.xml*
- *Added FuncUtilsTest and JSONUtilsTest  to verify the change.*
> Add the UTs of FuncUtils and JSONUtilsTest.

- script/scp-hosts.sh
*scp ui folder to install path*
*scp ui folder to install path*
> scp ui folder to install path

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/PropertyUtils.java
- dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/PropertyUtilsTest.java
- dolphinscheduler-alert/src/test/resources/alert.properties
- pom.xml
For #1465.
1. Add PropertyUtilsTest
2. Add null check and parse format check in PropertyUtils
3. Add UT path in parent.pom
- *Add PropertyUtilsTest*
- *Edit PropertyUtils*
- *Add alert.properties to src/test/resources*
- *Add UT path to root pom.xml*
- *Added PropertyUtilsTest to verify the change.*
> Add PropertyUtilsTest, the UT of PropertyUtils

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
*modify FileUtils.readFile2Str*
- *modify FileUtils.readFile2Str*
> modify FileUtils.readFile2Str

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/SparkArgsUtils.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/SparkArgsUtilsTest.java
- pom.xml
For #1465.
1.Add SparkArgsUtilsTest
2.Optimize SparkArgsUtils
3.Add the UT path in pom
- *Add SparkArgsUtilsTest.java*
- *Edit SparkArgsUtils.java*
- *Add UT path to root pom.xml*
- *Added SparkArgsUtilsTest to verify the change.*
> Add SparkArgsUtilsTest which is the UT of SparkArgsUtils

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/enums/ExecuteTypeTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/enums/StatusTest.java
- pom.xml
- add Status class unit test
- add ExecuteType class unit test
- *Add StatusTest.java*
- *Add ExecuteType.java*
- *Optimize Status*
- *Add UT path to root pom.xml*
- *Added ExecuteType to verify the change.*
- *Added StatusTest to verify the change.*
> Add Status and ExecuteType class unit tests #1465

- dolphinscheduler-dist/dolphinscheduler-backend/src/main/release-docs/LICENSE
*Add space or colon*
*Add space or colon*
> Add space or colon

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/Server.java
This pull request fixes a spell bug
- fix directory spell bug
> fix 'directory' spell bug

- dolphinscheduler-alert/pom.xml
- dolphinscheduler-api/pom.xml
- dolphinscheduler-common/pom.xml
- dolphinscheduler-dao/pom.xml
- dolphinscheduler-dist/dolphinscheduler-backend/pom.xml
- dolphinscheduler-dist/dolphinscheduler-front/pom.xml
- dolphinscheduler-dist/dolphinscheduler-src/pom.xml
- dolphinscheduler-dist/pom.xml
- dolphinscheduler-rpc/pom.xml
- dolphinscheduler-server/pom.xml
- dolphinscheduler-ui/pom.xml
- pom.xml
*reset pom to version 1.2.0-SNAPSHOT*
*reset pom to version 1.2.0-SNAPSHOT*
> reset pom to version 1.2.0-SNAPSHOT

- dolphinscheduler-dist/pom.xml
- dolphinscheduler-dist/src/main/assembly/dolphinscheduler-binary.xml
- dolphinscheduler-dist/src/main/assembly/dolphinscheduler-nginx.xml
*update assemble and rpmbuild because config/*.* remove script to dolphinscheduler-server/src/main/resources*
*update assemble and rpmbuild because config/*.* remove script to dolphinscheduler-server/src/main/resources*
*execute `mvn clean package -Prelease` or `mvn clean package -Pnginx` or `mvn clean package -Prpmbuild`*
the config/*.* will include the conf folder
> update assemble and rpmbuild in order to include the files of config

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/AlertManager.java
https://github.com/apache/incubator-dolphinscheduler/issues/1595
> [fix] process instance alert bug #1595

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/AbstractZKClient.java
E.g:
node1 ip : 192.168.1.6
node2 ip : 192.168.1.61, failed at startup.
> fix：In a cluster environment, verify that nodes have matching bug. #{1613}

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtils.java
fix sonarcloud bug 
#1632 
1. file:    dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtils.java
bug:  
-  https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&issues=AW9PvkP_YzPBRjkobY7y&open=AW9PvkP_YzPBRjkobY7y
-  https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&issues=AW9PvkP_YzPBRjkobY7z&open=AW9PvkP_YzPBRjkobY7z
2. file:    dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java
bug:  
- https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&issues=AW9PvkRwYzPBRjkobY87&open=AW9PvkRwYzPBRjkobY87
re analyzed by sonarcloud, the 3 bugs war fixed
>     fix sonarcloud bug 

- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/threadutils/ThreadUtilsTest.java
> add UT for common thread  package 

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/MonitorService.java
> fix Monitor bug

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/SchemaUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/SchemaUtilsTest.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/TaskParametersUtilsTest.java
refer #1465 
* Added SchemaUtilsTest.java TaskParametersUtilsTest.java ut
> SchemaUtils.java TaskParametersUtils.java unit test

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ParamUtils.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/ParamUtilsTest.java
- pom.xml
For #1465.
1. Add ParamUtilsTest.
2. Add a null check in the method convert.
3. Add the UT path to the root pom.
- *Add ParamUtilsTest.java*
- *Edit ParamUtils.java*
- *Add the UT path to root pom.xml*
- *Added ParamUtilsTest to verify the change.*
> Add ParamUtilsTest which is the UT of ParamUtils

- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/ParamUtilsTest.java
Fix bug in #1634 ,replace the current datetime with a fixed time
- *Edit ParamUtilsTest.java*
- *ParamUtilsTest to verify the change.*
> Fix bug in #1634 ,replace the current datetime with a fixed time

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/queue/TaskQueueZkImpl.java
*get root path from zookeeper config*
*get root path from zookeeper config*
> get root path from zookeeper config

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
*#1704 fix bug: delete process definition when a task aleady exec by worker lead to NPE*
- *Edit dao/ProcessDao*
> fix bug: delete processdefinition when a task aleady exec by worker lead to NPE

- dolphinscheduler-api/pom.xml
- pom.xml
Reverts apache/incubator-dolphinscheduler#1712
> Revert "move version to parent pom"

- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/PreconditionsTest.java
> commom/Preconditions Util Test

- dolphinscheduler-dist/release-docs/LICENSE
*check license and update*
*check license and update*
> check license and update

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/queue/TaskQueueZkImpl.java
*Fixed tasks_queue and tasks_kill did not exist in zookeeper #1696*
*Fixed tasks_queue and tasks_kill did not exist in zookeeper #1696*
> Fixed tasks_queue and tasks_kill did not exist in zookeeper #1696

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/SecurityConfig.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterBaseTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterSchedulerThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/quartz/DruidConnectionProvider.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/quartz/QuartzExecutors.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/rpc/LogClient.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
*#1740 ds.server regularize log print*
- *server/master*
- *server/quartz*
- *server/rpc*
- *server/utils*
> ds.server regularize log print

- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
*fix bug: fix ResourcesServiceTest*
> fix bug: fix ResourcesServiceTest

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/zk/AbstractZKClient.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/zk/ZKMasterClient.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/zk/ZKWorkerClient.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/EnvFileTest.java
*#1740 ds.server & ds.common regularize log print*
- *Edit common/zk*
- *Edit server/worker*
> ds.server & ds.common regularize log print

- dolphinscheduler-ui/src/js/conf/login/App.vue
- dolphinscheduler-ui/src/js/module/io/index.js
*fix: login interface cannot jump to home interface*
- *Add SessionId comparison logic in ui module*
> fixbug: login interface cannot jump to home interface

- pom.xml
*upgrade jackson from 2.9.8 to 2.10.1*
*upgrade jackson from 2.9.8 to 2.10.1*
> upgrade jackson from 2.9.8 to 2.10.1

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/ProcessMeta.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/exportprocess/DataSourceParam.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/exportprocess/DependentParam.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/exportprocess/TaskNodeParamFactory.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/exportprocess/exportProcessAddTaskParam.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/exportprocess/DataSourceParamTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/exportprocess/DependentParamTest.java
- pom.xml
*refactor export process*
- *Add api/dto/ProcessMeta*
- *Add api/utils/exportprocess/DataSourceParam*
- *Add api/utils/exportprocess/DependentParam*
- *Add api/utils/exportprocess/TaskNodeParamFactory*
- *Add api/utils/exportprocess/exportProcessAddTaskParam*
- *Edit api/service/ProcessDefinitionService*
This pull request is already covered by ProcessDefinitionServiceTest.testAddTaskNodeSpecialParam
> refactor export process 

- .github/workflows/ci_ut.yml
#1465 
maven batch mode option
> maven batch mode

- pom.xml
*add pom mysql test*
- *add pom mysql test*
> add pom mysql test

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/queue/TaskQueueZkImpl.java
*fix bug: zk hasTask method NPE*
- *Edit common/queue/TaskQueueZkImpl.hasTask method*
> fix bug: zk hasTask method NPE

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ResourceMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ResourceMapper.xml
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ResourceMapperTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskScheduleThread.java
*add check download resource permission in order to fix issues 1770*
*add check download resource permission in order to fix issues 1770*
- *Add method listUnauthorizedResource to ProcessDao*
- *Add method getUserById to ProcessDao*
- *Add listAuthorizedResource to ResourceMapper*
> add check download resource permission in order to fix issues 1770

- CONTRIBUTING.md
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/FetchTaskThread.java
fix #1775 bug，delete process definition when process instance is running
> fix #1775 bug，delete process definition when process instance is running

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/ProcessDao.java
*update method listUnauthorizedResource in order to fix issues 1770*
*update method listUnauthorizedResource in order to fix issues 1770*
> update method listUnauthorizedResource in order to fix issues 1770

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UdfFuncService.java
*if login user is admin,it will has permission to query all udf function*
*if login user is admin,it will has permission to query all udf function*
> if login user is admin,it will has permission to query all udf function

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/runner/AlertSender.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/ExcelUtils.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/MailUtils.java
*add retMap null check for AlertSender*
- *alert/runner/AlertSender*
- *alert/utils/ExcelUtils*
- *alert/utils/MailUtils*
> add retMap null check for AlertSender

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/ProcessMeta.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/FileUtils.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/exportprocess/DataSourceParam.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/exportprocess/DependentParam.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/exportprocess/ProcessAddTaskParam.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/exportprocess/TaskNodeParamFactory.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/FileUtilsTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/exportprocess/DataSourceParamTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/exportprocess/DependentParamTest.java
*refactor import process*
*#1803 remove old project permission check*
- *Modify api/dto/ProcessMeta*
- *Modify api/service/ProcessDefinitionService*
- *Modify api/utils/FileUtils*
- *Modify api/utils/exportprocess/DataSourceParam*
- *Modify api/utils/exportprocess/DependentParam*
- *Modify exportprocess/ProcessAddTaskParam*
- *Modify api/service/ProcessDefinitionServiceTest*
- *Modify api/utils/exportprocess/DataSourceParamTest*
- *Modify api/utils/exportprocess/DependentParamTest*
- *ProcessDefinitionServiceTest,DataSourceParamTest,DependentParamTest verify this change*
> refactor import process

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
*add null check when import process has sub-process*
- *api/service/ProcessDefinitionService.importSubProcess method*
This pull request is already covered by existing tests, such as *api.service.testImportSubProcess*.
> add null check when import process has sub-process

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/resources.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/spark.vue
This PR is a subtask of #1675.
Implements the spark and flink type task, now they can be cache the previous input.
- *Edit resources.vue*
- *Edit flink.vue*
- *Edit spark.vue*
> Implements the spark and flink type task, now they can be cache the previous input

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/manager/EnterpriseWeChatManager.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/runner/AlertSender.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/template/AlertTemplate.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtils.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/MailUtils.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/PropertyUtils.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/FileUtils.java
*null check in markdownTable*
- *add null check in markdownTable*
- *modify EnterpriseWeChatManager logger*
> add null check in markdownTable&modify EnterpriseWeChatManager logger

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
- dolphinscheduler-ui/src/js/conf/home/store/dag/actions.js
Fix  the bug in #1795, add a instance cache.
- *Edit actions.js*
> fix bug, add the cache logic in getInstancedetail

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/dependItemList.vue
fix the bug #1816. 
- *Edit dependItemList.vue*
> fix the bug #1816

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/ClickHouseDataSource.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/HiveDataSource.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/MySQLDataSource.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/OracleDataSource.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/PostgreDataSource.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/SQLServerDataSource.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/SparkDataSource.java
replace strings with constants already exist.
> replace strings with constants already exist.

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/PythonCommandExecutor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/ShellCommandExecutor.java
https://github.com/apache/incubator-dolphinscheduler/issues/1831
> [Feature] AbstractCommandExecutor.commandType difficult to understand

- dolphinscheduler-dist/pom.xml
> rpm package add UI

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/FourLetterWordMain.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
#1714 
Fix bug: Use try-with-resources or close this "Socket" in a "finally" clause. 
1. Use try-with-resources with Socket, prepareStatement.
2. Add connection.close() at executeFuncAndSql.
3. Fix some code smell.
> Fix bug: Use try-with-resources or close this "Socket" in a "finally" clause. 

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/DateInterval.java
1. Fix ExecutorService.java  return error, add return 0
2. Fix DateInterval.java obj error,  replace o to obj
> Fix return, obj error

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/SchedulerService.java
https://github.com/apache/incubator-dolphinscheduler/issues/1860
> [Feature] createSchedule should return schedule's Id

- dolphinscheduler-common/src/main/resources/quartz.properties
issue: https://github.com/apache/incubator-dolphinscheduler/issues/1863
> [Feature] set acquireTriggersWithinLock true

- dolphinscheduler-api/pom.xml
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
#1864  fix dependency and createCommand date check
1. Add server dependency in pom at api directory.
2. Remove start and end null check at line 502 to 505. line 504 checked
>  fix dependency and createCommand date check

- README.md
> fix wrong subscribe url

- README_zh_CN.md
> fix wrong upgrade url

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/MailUtils.java
add log, don't swallow exception info
> small fix: add log, don't swallow exception info

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/ZooKeeperState.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/DateInterval.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/TaskNodeRelation.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java
*Class overrides equals() and should therefore also override hashCode()*
- *Edit api/utils/ZooKeeperState*
- *Edit common/model/DateInterval*
- *Edit common/model/TaskNodeRelation*
- *Edit server/master/runner/MasterTaskExecThread*
> add hashCode

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
*change datasource null check position*
- *Edit server/worker/task/sql/SqlTask*
> change datasource null check position

- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LogClientService.java
- dolphinscheduler-ui/src/js/conf/login/App.vue
- dolphinscheduler-ui/src/js/module/io/index.js
refactor-logger branch login error modify
> refactor-logger branch login error modify

- dolphinscheduler-dist/release-docs/LICENSE
*check LICENSE file in order to consist of all lib jars*
- *update jackson version from 2.9.8 to 2.10.1*
- *change aws-sdk-java to aws-java-sdk*
- *change commans-net to commons-net*
> check LICENSE file in order to consist of all lib jars

- ReleaseNotes.md
- pom.xml
*update release notes and modify the plugin of rat*
*mvn  clean apache-rat:check*
> update release notes and modify the plugin of rat

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ScriptRunner.java
#1701 Resources should be closed
1. Use try-with-resources with Statement and ResultSetk.
2. Fix some code smell.
>  Fix bug: Use try-with-resources or close this "Statement" in a "finally" clause.

- dolphinscheduler-alert/pom.xml
- dolphinscheduler-api/pom.xml
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
- dolphinscheduler-common/pom.xml
- dolphinscheduler-dao/pom.xml
- dolphinscheduler-dist/pom.xml
- dolphinscheduler-rpc/pom.xml
- dolphinscheduler-server/pom.xml
- dolphinscheduler-ui/pom.xml
- pom.xml
*get authorized udf resources need exclude all created by self*
*get authorized udf resources need exclude all created by self*
> get authorized udf resources need exclude all created by self

- NOTICE
- dolphinscheduler-dist/release-docs/NOTICE
*update notice year form 2019 to 2019-2020*
*update notice year form 2019 to 2019-2020*
> update notice year form 2019 to 2019-2020

- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/ScriptRunnerTest.java
#1465 
add ScriptRunnerTest.java unit test
> add ScriptRunnerTest.java unit test

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/BaseController.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/placeholder/BusinessTimeUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/queue/BaseTaskQueueTest.java
Adapting partial code(file name start with B) to the sonar cloud rules
> Adapting partial code(file name start with B) to the sonar cloud rules

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/dependent.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/mr.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/procedure.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/python.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/shell.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/spark.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sub_process.vue
For #1675.
Continue to finish the rest works, add the cache feature for dependence, mr, python, sub_process,
procedure and shell.
- *Edit dependent.vue*
- *Edit mr.vue*
- *Edit python.vue*
- *Edit sub_process.vue*
- *Edit procedure.vue*
- *Edit shell.vue*
- *Edit spark.vue*
- *Edit flink.vue*
> Add the cache feature for dependence, mr, python, sub_process, procedure and shell.

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ResInfo.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/ResInfoTest.java
#1465 
add ResInfoTest.java ut
> add ResInfoTest.java ut

- .github/workflows/ci_ut.yml
#1465 
fix powermock coverage 0
> fix powermock coverage 0

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataAnalysisService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataAnalysisServiceTest.java
- pom.xml
For #1465
modify DataAnalysisServiceTest 
modify DataAnalysisService
modify root pom
`<include>**/api/service/DataAnalysisServiceTest.java</include>`
> modify DataAnalysisServiceTest by mock

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
*add release state null check & process definition UT*
- *add release state null check*
- *add process definition UT*
This pull request is already covered by existing tests, such as *ProcessDefinitionServiceTest*.
> add release state null check & process definition UT

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/Constants.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/CheckUtils.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/CheckUtilsTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/job/db/ClickHouseDataSource.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/subprocess/SubProcessParameters.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CollectionUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CommonUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/CollectionUtilsTest.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/CommonUtilsTest.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/OSUtilsTest.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/ConnectionFactory.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/CommandMapper.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/cron/CronUtils.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/cron/CycleFactory.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/cron/CronUtilsTest.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ConnectionFactoryTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
Adapting partial code(file name start with C) to the sonar cloud rules
> Adapting partial code(file name start with C) to the sonar cloud rules

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/FourLetterWordMain.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/FourLetterWordMainTest.java
- pom.xml
#1889 
Fix get wrong zk status with 4 letter command.
1. Read after sock connect.
2.  Add UT for FourLetterWordMain.
> Fix socket bug: read before sock connect. Add UT for FourLetterWordMain.

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.js
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/plugIn/jsPlumbHandle.js
Fix the bug #1968. 
When create a new task or edit an exist task.The task details window will be open.
Then if delete the task node or click the DataSource menu. And the task details window still open.
For now, the task details window will be close.
- *Edit dag.vue*
- *Edit dag.js*
- *Edit jsPlumbHandle.js*
> Fix the bug #1968.

- .github/workflows/ci_e2e.yml
- dockerfile/README.md
- dockerfile/hooks/build
- dockerfile/hooks/check
- dockerfile/startup.sh
#1460 
Support docker deploy for e2e test
> Support docker deploy for e2e test

- README.md
> system screenshot update

- README_zh_CN.md
I found that Readme.md still used EasyScheduler's image, I have updated
> update image in README_zh_CN.md

- README.md
small changes, some images not right，correct
> correct repeat images in README

- .github/workflows/ci_e2e.yml
- .github/workflows/ci_ut.yml
- e2e/pom.xml
- e2e/src/test/java/org/apache/dolphinscheduler/base/BaseDriver.java
- e2e/src/test/java/org/apache/dolphinscheduler/data/LoginData.java
- e2e/src/test/java/org/apache/dolphinscheduler/data/security/TenantManageData.java
- e2e/src/test/resources/config/config.properties
- e2e/testng.xml
> docker and testcase config for e2e test

- README.md
> update wechat id

- README.md
image about monitor screenshot is wrong
> image about monitor screenshot is wrong

- README.md
> repeat image

- .github/workflows/ci_backend.yml
test and modify frontend action build failed
> modify action build

- .github/workflows/ci_backend.yml
- .github/workflows/ci_e2e.yml
- .github/workflows/ci_frontend.yml
- .github/workflows/ci_ut.yml
Fix github action rerun failed 
#2052 
according to https://github.com/actions/checkout/issues/23 update actions/checkout@v1 to actions/checkout@v1.
modified files:
ci_backend.yml
ci_e2e.yml
ci_frontend.yml
ci_ut.yml
> Fix github action rerun failed 

- .github/workflows/ci_e2e.yml
- .github/workflows/ci_ut.yml
remove submodules for checkout v2
modified file
ci_e2e.yml
ci_ut.yml
> remove submodules for checkout v2

- .github/workflows/ci_backend.yml
- .github/workflows/ci_frontend.yml
- .github/workflows/ci_ut.yml
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
*Fix github action rerun failed*
*update resource service test*
> Fix github action rerun failed

- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/ZookeeperMonitorUtilsTest.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/AlertManager.java
- sql/upgrade/1.2.2_schema/mysql/dolphinscheduler_ddl.sql
- sql/upgrade/1.2.2_schema/postgresql/dolphinscheduler_ddl.sql
*#464 add workflow id, name for email content*
- *add workflow id, name for email content*
> add workflow id, name for email content

- .github/workflows/ci_e2e.yml
- .github/workflows/ci_ut.yml
> action push delete

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/config/MasterConfig.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/consumer/TaskUpdateQueueConsumer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistry.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/config/WorkerConfig.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistry.java
> Refactor worker

- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/zk/AbstractZKClient.java
> use stringbuilder to append string

- .asf.yaml
This pull request adds .asf.yaml file which will automatically trigger the update of some content of an apache project on GitHub.
Add .asf.yaml file under project root dir.
This pull request need to manually check if some update of new content occurred.
> add .asf.yaml file

- README.md
This pull request is error word correction and edit README.md file modify word from expand to extend.
Edit README.md file modify word from expand to extend.
This pull request is error word correction without any test coverage.
> Error word correction edit README.md file modify word from expand to extend

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/shell/AbstractShell.java
> use logger to print exception

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/ZooKeeperState.java
> fix field access modifier

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/MailUtils.java
> fix unequal number of arguments and placeholder

- dolphinscheduler-alert/src/main/resources/alert.properties
- install.sh
More tips for mail server configuration.
> Add mail server configuration description information

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/config.js
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
> fix: The toolbar buttons of Dag disable bug

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/datasource.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/conditions.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sqoop.vue
Add input cache for sqoop and conditions tasks.
- *formModel.vue*
- *sqoop.vue*
- *conditions.vue*
- *datasource.vue*
> Add input cache for sqoop and conditions tasks

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/thread/ThreadUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
> The master and worker server exit exception #2163

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
> fix: NullPointException in the case of task queuing #2174

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
- dolphinscheduler-common/src/main/resources/common.properties
> Cache HadoopUtils instance with specific days expire time

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
Change the two field from static to instance to avoid affecting the existing HadoopUtils instance when it's initializing a new instance.
*(or)*
(or)
*(example:)*
- *Manually verified the change by …
> change static field to instance field

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/TaskRecordDao.java
- e2e/src/test/resources/config/config.properties
> fix ResultSet not close and reformat code

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/ApiApplicationServer.java
> fix: Api server startup fail #2197

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/PropertyUtils.java
*  Optimize PropertyUtils instantiation.
>  Optimize PropertyUtils instantiation.

- e2e/src/test/java/org/apache/dolphinscheduler/testcase/LoginTest.java
> add LoginTest license

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingClient.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/handler/NettyServerHandler.java
> fix blocker problem

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AlertGroupController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/AlertGroupService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UserAlertGroupService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AlertGroupServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UserAlertGroupServiceTest.java
- pom.xml
optimizing AlertGroupService#grantUser by batch insert into db.
AlertGroupServiceTest#testGrantUser
*(example:)*
> feat:optimizing code

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
> fix：Depend check bug

- .github/workflows/ci_ut.yml
- ambari_plugin/common-services/DOLPHIN/1.2.1/package/scripts/params.py
- docker/docker-compose.yml
- dolphinscheduler-remote/pom.xml
- dolphinscheduler-service/pom.xml
- dolphinscheduler-ui/src/lib/external/config.js
- dolphinscheduler-ui/src/lib/external/email.js
- e2e/pom.xml
- e2e/testng.xml
- pom.xml
> license and checkoutv2 fix

- .github/workflows/ci_ut.yml
refactor worker ci ut yml modify
> refactor worker ci ut yml modify

- .github/workflows/ci_e2e.yml
- dockerfile/hooks/check
add ds logs and server status check
> add ds logs and server status check

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ResourceMapper.xml
*need query all authorized directory children when create task*
*need query all authorized directory children when create task*
> need query all authorized directory children when create task

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
*It's fixed that resource not deleted in hdfs when delete it.*
*It's fixed that resource not deleted in hdfs when delete it.*
> It's fixed that resource not deleted in hdfs when delete it.

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/shell/ShellTask.java
Resolved nullpointerexception caused by no checks taskProps.getScheduleTime() when shell task
building the command
> resolve shell task build command nullpointexception

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/ProcessMeta.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/process/ProcessEnvironmentForWin32.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/process/ProcessImplForWin32.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessInstance.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapMapperTest.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapperTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
https://github.com/apache/incubator-dolphinscheduler/pull/2213
> Adapting partial code(file name start with P #2) to the sonar cloud rule

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
> fix：Optimize content returned by interface #2292

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
> sql task, query type, use column label #2334

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/ExcelUtils.java
- dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/ExcelUtilsTest.java
> fix：mail send fail #2345

- .mvn/jvm.config
- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- README.md
- README_zh_CN.md
- mvnw
- mvnw.cmd
This pull request adds maven-wrapper support.
- Add maven-wrapper support for dolphinscheduler.
> Add maven-wrapper support for dolphinscheduler.

- .asf.yaml
Update project label in .asf.yaml
> Update project label in .asf.yaml

- .asf.yaml
> upadte project label .asf.yaml

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/template/AlertTemplateFactory.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/Constants.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/MailUtils.java
- dolphinscheduler-alert/src/main/resources/alert.properties
- dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/template/AlertTemplateFactoryTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
- dolphinscheduler-common/src/main/resources/common.properties
- dolphinscheduler-dao/src/main/resources/datasource.properties
- dolphinscheduler-server/src/main/resources/config/install_config.conf
- install.sh
- script/dolphinscheduler-daemon.sh
- script/scp-hosts.sh
- script/start-all.sh
- script/stop-all.sh
> [Refactor worker] simplify and optimize config

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SpringConnectionFactory.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UserMapperTest.java
*To fix the transaction didn't work*
*It's to remove `static` of method dataSource*
- * remove `static` of method dataSource in SpringConnectionFactory*
> It's to remove `static` of method dataSource,If not remove `static` the transaction will not work.

- sql/upgrade/1.2.2_schema/mysql/dolphinscheduler_ddl.sql
- sql/upgrade/1.2.2_schema/postgresql/dolphinscheduler_ddl.sql
*add worker_group field and remove worker_group_id field of the table t_ds_command and t_ds_error_command*
> update  table t_ds_command and t_ds_error_command

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
*Solve the failure to execute non-query sql*
- move resultSet = stmt.executeQuery() into SqlType.QUERY branch
> Solve the failure to execute non-query sql

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
- sql/upgrade/1.2.2_schema/mysql/dolphinscheduler_ddl.sql
- sql/upgrade/1.2.2_schema/postgresql/dolphinscheduler_ddl.sql
*fix NPE when grant resource or save process definition*
*fix NPE when grant resource or save process definition*
*change worker_group from 255 to 64*
> fix NPE when grant resource or save process definition

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AlertGroupController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataAnalysisController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataSourceController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoggerController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoginController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/MonitorController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/QueueController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskInstanceController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskRecordController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TenantController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkerGroupController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/exceptions/ApiExceptionHandler.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/exceptions/ApiExceptionHandlerTest.java
Update all controllers with `ApiException` annotation. more details can refer to #2397 .
- Update Controllers in api package
- Optimise ApiExceptionHandler
> update controllers with ApiException annotation

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/gantt/_source/gantt.js
> fix: Gantt chart bug #2439

- pom.xml
> exclude HadoopUtils Test

- pom.xml
> add include HadoopUtils.java

- kubernetes/dolphinscheduler/requirements.yaml
*This pull request add  kubernetes/dolphinscheduler/requirements.yaml license*
> add license

- docker/docker-swarm/docker-stack.yml
- docker/docker-swarm/dolphinscheduler_env.sh
- dockerfile/Dockerfile
- dockerfile/conf/dolphinscheduler/env/dolphinscheduler_env.sh
- dockerfile/conf/dolphinscheduler/logback/logback-alert.xml
- dockerfile/conf/dolphinscheduler/logback/logback-api.xml
- dockerfile/conf/dolphinscheduler/logback/logback-master.xml
- dockerfile/conf/dolphinscheduler/logback/logback-worker.xml
- dockerfile/startup.sh
> Use docker-compose for deployment . Failed to execute python script

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
*This pull request fix copy workflow tip. #2578*
> fix copy workflow tip

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
1 Modify tenant and queue options to be the same length
2 Modify the prompt message when the user does not select the queue
https://github.com/apache/incubator-dolphinscheduler/pull/2558#issuecomment-625048616
> modify the prompt message when the user does not select the queue

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- sql/dolphinscheduler_mysql.sql
fix #2559
1. unique check before import ProcessDefinitions
2. add unique key on name and project_id
> unique check before import ProcessDefinitions

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
> Fix notes#2603

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
fix code annotation error(#2603)
> fix code annotation error

- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
fix script variable has "processDefinitionId" is error #2664
> script variable has "processDefinitionId" is error #2664

- dolphinscheduler-alert/src/main/resources/logback-alert.xml
> Modify the alert log file

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/template/impl/DefaultHTMLTemplate.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ExecutionStatus.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
blank in eamil and left font align #2648
> blank in eamil and left font align #2648

- .github/workflows/ci_e2e.yml
- docker/docker-swarm/check
- docker/docker-swarm/docker-compose.yml
- docker/docker-swarm/docker-stack.yml
- docker/kubernetes/dolphinscheduler/values.yaml
- dockerfile/Dockerfile
- dockerfile/hooks/build
1. Fix zookeeper health check
2. Merge volumes into logs volume
3. Modify `dockerfile/hooks/build` script
#2640
> fix zookeeper health check and merge volumes into logs volume

- .github/workflows/ci_ut.yml
- docker/docker-swarm/docker-compose.yml
- dockerfile/Dockerfile
- dockerfile/startup.sh
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapperTest.java
- sql/upgrade/1.3.0_schema/postgresql/dolphinscheduler_ddl.sql
1. add initdb volume for pg service in docker-compose.yml
2. modify ci_ut.yml
> Using docker/docker-swarm/docker-compose.yml to run pg and zk in ci_ut.yml

- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/log/LoggerServerTest.java
- pom.xml
> add LoggerServerTest UT

- dolphinscheduler-common/src/main/resources/common.properties
- dolphinscheduler-server/src/main/resources/config/install_config.conf
> Modify HDFS/S3 path

- dolphinscheduler-server/src/main/resources/config/install_config.conf
> set worker group 

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
*fix #2598:allow to update resource suffix,but if it is authorized to other users,it is not allowed.*
*add RESOURCE_IS_AUTHORIZED status*
*support update resource suffix*
> fix #2598::allow to update resource suffix,but if it is authorized to other users,it is not allowed

- dolphinscheduler-common/pom.xml
the license about janino maybe not compatiable with Apache v2
> remove codehaus janino jar

- tools/dependencies/known-dependencies.txt
remove commons-compiler-3.0.12.jar
> remove commons-compiler-3.0.12.jar  from known-dependencies.txt

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
*fix 2598:change getId to getUserId*
*fix 2598:change getId to getUserId*
> fix 2598:change getId to getUserId

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManager.java
* NettyExecutorManager.execute logic is not graceful , using LinkedList to make it readable 
-  NettyExecutorManager.execute()
> simply NettyExecutorManager.execute logic making it readable

- .github/workflows/ci_e2e.yml
> update e2e chrome version

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
*This pull request fix the sql task bug #2739*
> fix sql task bug #2739

- ambari_plugin/README.md
Modify the ambari-plugin readme for packing RPM packages and add a description of the replication plug-in directory
> Modify the ambari-plugin readme 

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ResInfo.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistry.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistry.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/zk/AbstractZKClient.java
- dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/master.vue
- dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/worker.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
bug fix[#2735 ](https://github.com/apache/incubator-dolphinscheduler/issues/2735)
1. store process id in zk.
2. resolve host and port through zk path.
3. modify ui key.
> fix [BUG]The IP and process pid of the master and worker in the monitoring center are not displayed

- sql/upgrade/1.3.0_schema/mysql/dolphinscheduler_ddl.sql
- sql/upgrade/1.3.0_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.3.0_schema/postgresql/dolphinscheduler_ddl.sql
- sql/upgrade/1.3.0_schema/postgresql/dolphinscheduler_dml.sql
*get  worker group name value and  change worker_group_id to worker_group *
*get  worker group name througth query the table t_ds_worker_group*
*change worker_group_id to worker_group*
> get  worker group name value and  change worker_group_id to worker_group 

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataSourceController.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/OracleDataSource.java
*use method getJdbcUrl of parent*
*remove the incorrect print message*
*use method getJdbcUrl of parent*
*Remove the incorrect print message*
> fix oracle connect failure

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/OracleDataSource.java
*When update the data source,the host and port show error*
*When update the data source,the host and port show error*
> When update the data source,the host and port show error

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskCallbackService.java
fix bug(#2836 )  send task result to master until success.
> fix bug: send task result to master until success.

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/ShellCommandExecutor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/datax/DataxTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/shell/ShellTask.java
1. DS cant run bat script
2. DS cant run python script
3. DS cant run datax script
#2841
> Fix errors when running on win10

- LICENSE
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ScriptRunner.java
- licenses/LICENSE-mybatis.txt
- pom.xml
*add source license full text into source license*
*add source license full text into source license*
> add source license full text into source license

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/DolphinSchedulerManager.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/UpgradeDao.java
*#2835 fix init db metadata error*
- *Modify DolphinSchedulerManager*
- *Modify UpgradeDao*
- *this pr have tested in mysql5.6 & pg 11.2*
> fix table not exist when init db metadata

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
Improve the security of datasource management
Closes #2638 Improve the security of datasource management
1. Datasource info page not exposed password.
2. Update datasource no password parameter，use old password。
> fix: Improve the security of datasource management

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
- dolphinscheduler-common/src/main/resources/common.properties
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/HadoopUtilsTest.java
add job history status url to judge application status, when application number threshold is reached(default 10000,maybe it was set to 1000).
you can see issue #2625
> add job history to judge application status/2625

- dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/JSONUtilsTest.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/exportprocess/DataSourceParam.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/exportprocess/DependentParam.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/exportprocess/DataSourceParamTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/exportprocess/DependentParamTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StreamUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/JSONUtilsTest.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/ParameterUtilsTest.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/StreamUtilsTest.java
- Updated JSONUtils, deprecated Fastjson and use jackson
- Added some tests
> Using Jackson instead of Fastjson

- sql/upgrade/1.3.0_schema/mysql/dolphinscheduler_ddl.sql
- sql/upgrade/1.3.0_schema/postgresql/dolphinscheduler_ddl.sql
*modify t_ds_task_instance app_link change sql*
- *modify t_ds_task_instance app_link change sql*
- *tested in mysql5.6 & pg9.6*
> modify t_ds_task_instance app_link change sql

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskCallbackService.java
change max length of user name to 39(#2855)
> change max length of user name to 39

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
*copy resources need get top directory first*
*copy resources need get top directory first*
> copy resources need get top directory first

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
*fix #2860:copy files and create empty directory*
*fix #2860:copy files and create empty directory*
> fix #2860:copy files and create empty directory

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/permission/PermissionCheck.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
*Fix bug:If user didn't set the value of tenant,release process definition fail*
*Fix bug:If user didn't set the value of tenant,release process definition fail*
> Fix bug:If user didn't set the value of tenant,release process definition fail

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
fix [BUG] When editing user information, clear the phone number, the database table t_ds_user.phone is not cleared #2892
*(or)*
(or)
*(example:)*
- *Added CronUtilsTest to verify the …
> merge method updateuser if and fix bug#2892

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sqoop/generator/sources/MysqlSourceGenerator.java
*#2893 fix bug: sqoop mysql import params error*
- *Modify sqoop import mysqlGenerator*
> fix bug: sqoop mysql import params error

- README.md
- README_zh_CN.md
*update how to build and remove docs link*
*update how to build and remove docs link*
> update how to build and remove docs link

- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
> Fix tasks not execute in sub-process when rerun scheduled process. #2903

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/datax/DataxParameters.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/datax/DataxTask.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/datax/DataxTaskTest.java
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/datax.vue
1.Compatible with existing datax tasks
2.Local params UI bug
> Fixbug datax task

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/http/HttpParameters.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/task/HttpParametersTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/http/HttpTask.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/http/HttpTaskTest.java
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/http.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
- pom.xml
> add http task timeout & test unit

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingServer.java
remove unnecessary code
- remove unnecessary code from NettyRemotingServer.java
> first show: remove unnecessary code

- NOTICE
*add mybatis-3 notice in the top-level notice*
*add mybatis-3 notice in the top-level notice*
> add mybatis-3 notice in the top-level notice

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/JSONUtilsTest.java
*Fix Jackson user defined deserializer error*
- *Change `org.apache.dolphinscheduler.common.utils.JSONUtils.JsonDataDeserializer#deserialize()` function implement*
- *Delete the use of fastjson in `org.apache.dolphinscheduler.common.utils.JSONUtilsTest`*
- *Added *org.apache.dolphinscheduler.common.utils.JSONUtilsTest#jsonDataDeserializerTest()* to verify the change.*
> [Hotfix-2922][common] Fix Jackson UDde error (#2922)

- NOTICE
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
*fix download resource file that under the directory error*
*fix download resource file that under the directory error*
> fix download resource file that under the directory error

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/codec/NettyDecoder.java
edit duplicate DOLPHIN_ALERT and label
> Fix bug #2991 duplicate key: DOLPHIN_ALERT

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
https://github.com/apache/incubator-dolphinscheduler/issues/2983
> always send emails no matter there are results

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/list.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Fix Issue #3018 
modified the filed of 'user type' in dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/list.vue
add translate to dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
add translate to dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
> Fix #3018 [BUG_i18n incomplete] 

- dolphinscheduler-api/src/main/resources/application-api.properties
issues : #3001
Solution: Spring serializes Java's date type date problem
> Solution: Spring serializes Java's date type date problem

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
fix issue #3017 
correct the error comment about ‘create resource’ to ‘create directory’
> Fix Issue #3017

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/CheckUtils.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskInfo.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/entity/TaskExecutionContext.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/NettyRemoteChannel.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskCallbackService.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/processor/TaskCallbackServiceTest.java
*Revise annotation spelling errors*
*Enhanced code robustness*
> Revise annotation spelling errors & Enhanced code robustness

- ambari_plugin/README.md
The configuration of environment variables in A DS project is often inconsistent with the actual environment. And instructions to modify environment variables when AMbari installs DS are added to the documentation
> [feature] readme.md adds instructions for changing environment variables

- .github/workflows/ci_e2e.yml
- .github/workflows/ci_ut.yml
*update ci from dev-1.3.0*
*update ci from dev-1.3.0*
> update ci from dev-1.3.0

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstance.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/entity/TaskExecutionContext.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
*fix 2975:download resource need find the tenant code of resource owner*
*download resource need find the tenant code of resource owner*
> fix 2975:download resource need find the tenant code of resource owner

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/resources/Directory.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/resources/FileLeaf.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/resources/ResourceComponent.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/resources/visitor/Visitor.java
*update license header location*
*update license header location*
> update license header location

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/exceptions/ExecuteException.java
> remove some notes

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CommonUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/Preconditions.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/PreconditionsTest.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/exceptions/RemotingException.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/future/ResponseFuture.java
fix Permission denied if not found dolphinscheder-env.sh
> fix Permission denied if not found dolphinscheder-env.sh on 1.3.1

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
> modify sqlTask.close()

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/AppConfiguration.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/UsersControllerTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
complete feature(#3123 )
- *add function in userController.java and userService.java*
- *add intecepter exclude path*
- *add releted unit test*
> [Feature-3123]user register

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingServer.java
fix #3157 
*(or)*
(or)
*(example:)*
> [Bug][Refactor][issue-3157]use cas to avoid thread safe problem

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
fix the bug #3181
dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
HadoopUtilsTest.java have cover the tests.
> Modify the AWS S3 request encryption method to V4.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/improvement_suggestion.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/test.md
*Add the issue template according to the issue specification*
- *Add `improvement_suggestion.md` and `test.md` issue templates*
- *Change `bug_report.md` and `feature_request.md` according issue specification*
> [Feature][docs] Add the issue template according to the issue specification

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/registry/ZookeeperNodeManager.java
There are some methods in ZookeeperNodeManager Class, these methods define local variables, but they have never been used, so I removed it
> [Improvement][Server]Code Clean

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/improvement_suggestion.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/test.md
*Add the `Issue` specifications reference*
https://dolphinscheduler.apache.org/en-us/docs/development/issue.html
- *Add https://dolphinscheduler.apache.org/en-us/docs/development/issue.html to all file of `ISSUE_TEMPLATE`*
> [Improvement][docs] Add the issue specifications reference

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java
[DagHelper]getFlowNodeListPost/getFlowNodeListPre time complexity is O(N^N); Thiss might solve the problem
Add vistied marked list to function getFlowNodeListPost/getFlowNodeListPre
> [Fix-3236][DagHelper]getFlowNodeListPost/getFlowNodeListPre time complexity O(N^N) 

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/MonitorService.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/WorkerServerModel.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistry.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/registry/HeartBeatTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/config/WorkerConfig.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistry.java
- dolphinscheduler-server/src/main/resources/worker.properties
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistryTest.java
- dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/_source/zookeeperDirectories.vue
- dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/worker.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
*cherry pick commit from dev for one worker can belong different worker groups*
*cherry pick commit from dev for one worker can belong different worker groups*
> [Feature-2815]cherry pick commit from dev for one worker can belong different worker groups

- docker/build/conf/nginx/dolphinscheduler.conf
/ui下的资源访问不应该发送到api-server
*(or)*
(or)
*(example:)*
> [Feature-docker][ui] Update dolphinscheduler.conf

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterSchedulerService.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/MasterExecThreadTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumerTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutorDispatcherTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/host/RoundRobinHostManagerTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThreadTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/registry/ZookeeperNodeManagerTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/processor/TaskCallbackServiceTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistryTest.java
- pom.xml
**Fix the github action oom #3288 **
- *Optimize the MasterExecThreadTest.java by using `PowerMock`*
- *Add the stopper to TaskPriorityQueueConsumerTest.java*
- *Add the `unregistry` function to release the resource in all test case which used the `registry`*
> [Test-3288][server] Fix github ci unit test oom

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
*This pull request fix issues #3295*
- *Modify SchedulerController.java*
*(This pull request is add default value without any test coverage.)*
> [Fix-3295][api] Add default value for request RequestParam

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/HttpUtilsTest.java
Implement the httpClient singleton model，and Support for insecure HTTPS
Improvement #3332
> [Improvement][common] HttpClient singleton mode #3332

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
*This pull request remove the duplicate function that  determine whether retry task exsits in MasterExecThread*
> [Fix][Master]remove the duplicate function in MasterExecThread

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
colse(#3077 )
*Fix the edit duplicated name verify* 
- *Change the verify for edit and create process definition*
> [Fix-3077][ui] Fix the edit duplicated name verify

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/ApiApplicationServer.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/AlertGroupService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/SchedulerService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/SessionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UdfFuncService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
*Improvement the transaction manage*
> [Improvement][api] Refactor the transaction rollbackfor runtimeexception

- dolphinscheduler-server/src/main/resources/config/install_config.conf
- install.sh
- script/remove-zk-node.sh
**implementation #3309  **
- *Add install_config zk root directory*
- *Add install.sh zkRoot sed*
- *Change remove-zk-node.sh use zk own del func*
> [Feature]use zk own del func

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/process/ResourceInfo.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumer.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
*Fix #3364 Running the spark task fail because the can't find the jar*
*update queryTenantCodeByResName in order to make this method compatible with the old version*
> [Fix-3364][service,server]Running the spark task fail because the can't find the jar

- script/dolphinscheduler-daemon.sh
JVM parameter optimization , related issue #3370
> [Feature] JVM parameter optimization , related issue #3370

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
*support re-upload the resource file*
*support re-upload the resource file*
> [Improvement-3327][api]support re-upload the resource file

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
fix bug(#3324 ) there exists some problems in checking task dependency
*(or)*
(or)
*(example:)*
> [BUG-3324][SERVER]: there exists some problems in checking task dependency

- ambari_plugin/common-services/DOLPHIN/1.3.2/configuration/dolphin-worker.xml
*[Feature][ambari_plugin]support one worker can belongs different worker group*
*change config worker.group to worker.groups*
> [Feature][ambari_plugin]support one worker can belongs different worker group

- dolphinscheduler-ui/src/js/conf/home/store/dag/actions.js
> [Fix-3351][ui] process_definition_json contains definitionList，but this definitionList is not use

- sql/upgrade/1.2.0_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.3.0_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.3.0_schema/postgresql/dolphinscheduler_dml.sql
* [Fix-3256][sql] cherry pick to fix admin user info update error*
* [Fix-3256][ui] Fix admin user info update error*
> [Fix-3256][sql] cherry pick tommit to fix admin user info update error (#3425)

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
*[Fix-3433][api]Fixed that release the imported process definition which version is below 1.3.0 will be failure*
*Fixed that release the imported process definition which version is below 1.3.0 will be failure*
> [Fix-3433][api]Fixed that release the imported process definition which version is below 1.3.0 will be failure

- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceControllerTest.java
- pom.xml
*Introduce api controller unit test example*
- *Improve ProcessInstanceControllerTest*
- *Format code style*
> [Test][api] Introduce api controller unit test example

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AccessTokenController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/AccessTokenService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AccessTokenServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AccessTokenServiceTest.java
*Introduce access token service interface for clear code*
- *Change AccessTokenService class to interface*
- *Introduce AccessTokenServiceImpl class for AccessTokenService interface*
- *Format the code style*
> [Improvement-3369][api] Introduce access token service interface for clear code

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoggerController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/exceptions/ApiExceptionHandler.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/LoggerService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/LoggerServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LogClientService.java
*Introduce logger service interface for clear code*
- *Change `LoggerService` class to interface*
- *Add isRunning for `LogClientService`*
> [Improvement-3369][api] Introduce logger service interface for clear code

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataAnalysisService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataAnalysisServiceTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/TriFunction.java
*Introduce data analysis service interface for clear code*
- *Change DataAnalysisService class to interface*
- *Add DataAnalysisServiceImpl class for DataAnalysisService interface*
- *Format the code style*
> [Improvement-3369][api] Introduce data analysis service interface for clear code

- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/log/LoggerServerTest.java
- pom.xml
*Add e2e LoggerServerTest for api and server*
- *Improvement and add LoggerServerTest to root pom.xml*
> [Test][server] Add e2e LoggerServerTest

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/interceptor/LoginHandlerInterceptor.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/BaseService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/SessionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SessionServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/SessionServiceTest.java
*Introduce session service interface for clear code*
- *Format `BaseService` code style*
- *Introduce `SessionServiceImpl`*
- *Change `SessionService` class to `SessionService` interface*
This pull request is already covered by existing tests.
> [Improvement-3369][api] Introduce session service interface for clear code

- style/checkstyle.xml
- style/intellij-java-code-style.xml
*Change checkstyle import order and indent*
- *Change checkstyle.xml*
> [Improvement][style] Improve checkstyle import order and code style importer

- docker/build/README.md
- docker/build/README_zh_CN.md
- docker/build/conf/dolphinscheduler/worker.properties.tpl
- docker/build/startup-init-conf.sh
- docker/docker-swarm/docker-compose.yml
- docker/docker-swarm/docker-stack.yml
- docker/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-worker.yaml
- docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
- docker/kubernetes/dolphinscheduler/values.yaml
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/Host.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/CommonHostManager.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/RandomHostManager.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/RoundRobinHostManager.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/RandomSelector.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/RoundRobinSelector.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/config/WorkerConfig.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistry.java
- dolphinscheduler-server/src/main/resources/worker.properties
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/RandomSelectorTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/RoundRobinSelectorTest.java
weight-based load balancing algorithm
this closes #3234
weight-based load balancing algorithm
Implementation of load balancing based on weight.
Implementation of load balancing based on workgroups.
Related mail：https://lists.apache.org/thread.html/r06af73b0897d8a0c97a16ca1b9316d5d0bc29de833f60c10ca46415a%40%3Cdev.dolphinscheduler.apache.org%3E
https://lists.apache.org/thread.html/r5a70a5f43aa49973923ef23d5b079b883cda746a14e91f9c083a985a%40%3Cdev.dolphinscheduler.apache.org%3E
this closes #3234
> [Feature#3234][cluster]enhanced load balancing

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
Description: Deep monitoring causes the node to request mutations twice
> [optimization][ui]Remove node deep monitoring

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/plugIn/jsPlumbHandle.js
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/plugIn/util.js
> [Fix-3058][ui]Method catches with variables

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UdfFuncService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UdfFuncServiceTest.java
*If login user is admin,need list all udfs*
*If login user is admin,need list all udfs*
> [Fix-3462][api]If login user is admin,need list all udfs

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistry.java
*This pull request fix zookeeper path end with / character error #3466*
> [Bug-3466][Worker]Fix zookeeper path end with / character error

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapper.xml
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapperTest.java
*Fixed that run the sql task will be failure after rename the udf resource*
*[Fix-3463][api]Fixed that run the sql task will be failure after rename the udf resource*
*add batchUpdateUdfFuncTest method*
> [Fix-3463][api][dao]Fixed that run the sql task will be failure after rename the udf resource

- .github/workflows/ci_e2e.yml
*fix ci_e2e fail*
*fix ci_e2e fail*
> fix ci_e2e fail

- .github/workflows/ci_e2e.yml
Reverts apache/incubator-dolphinscheduler#3497
> Revert "fix ci_e2e fail"

- style/checkstyle.xml
*Fix checkstyle static type order checker to match code-style import order*
> [Fix][checkstyle] Fix checkstyle static type order checker

- NOTICE
*remove OGNL part of the mybaits notice*
*remove OGNL part of the mybaits notice*
> remove OGNL part of the mybaits notice

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/AccessTokenService.java
modify general user can't create,delete,update token
> modify general user can't create,delete,update token

- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/AccessTokenMapperTest.java
- dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ResourceMapperTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/future/TaskFuture.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseService.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/quartz/QuartzExecutors.java
fix assert error(assertions always pass) .
use AtomicReference<Object> to replace unsafe volatile Object
lazy initialization holder class Singleton...(unsafe volatile Object)
#3321
> [Improvement][server] Fix some sonar analyzed bugs

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
such as the follow png, i think this should be 'getColumnLabel'，not 'getColumnName'
> [bug fix] [Server][sqlTask]The alias column in the query SQL does not take effect #3549

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/MailUtils.java
Optimize mail configuration parameters,If "mail.smtp.ssl.enable" property is false, No configuration required "mail.smtp.ssl.trust" .
>  #3542 Optimized mail configuration

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TenantController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TenantService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
*Introduce tenant service interface for clear code*
- *Introduce service interface*
- *format the code style of tenant service test*
> [Improvement-3369][api] Introduce tenant service interface for clear code

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingClient.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingServer.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/NettyUtils.java
- dolphinscheduler-remote/src/test/java/org/apache/dolphinscheduler/remote/NettyUtilTest.java
- pom.xml
improvement netty eventLoopGroup
If you are running on linux you can use EpollEventLoopGroup and so get better performance, less GC and have more advanced features that are only available on linux.
UT
> [Improvement][remote] improvement netty eventLoopGroup

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistry.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryTest.java
- pom.xml
* Add the master server test case *
- *Bring master registry test case back*
> [Test][server] Add the `server module` master server and `zk` e2e test case example

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtils.java
- dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtilsTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/AlertEvent.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/AlertWarnLevel.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessAlertContent.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ServerAlertContent.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/registry/ZookeeperNodeManager.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/AlertManager.java
Optimize alarm information
Complete the alarm message through the entity class
Optimize the host information and remove the ZK path
> [Improvement][alert]   Optimize alarm information

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
> [FIX][dolphinscheduler-common] presto array serialization error

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/UsersControllerTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
*https://github.com/apache/incubator-dolphinscheduler/issues/3567*
- *Add batchActivateUser function to api userController*
- *Add batchActivateUser to api  userService*
- *Add unit test to userControllerTest And userServiceTest*
- *Manually verified the change by testing locally, And add some unit test function*
> [Feature-3567] batch activate user

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/relatedItems.vue
- dolphinscheduler-ui/src/js/conf/home/store/dag/actions.js
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
> [Feature-2753][ui]batch copy or move process

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/versions.vue
*Fix version control online process definition editable* (#3607 )
- *`dag.vue` pass the releaseState and `version.vue` got the state and judge*
> [Fix-3607][ui] Fix version control online process definition editable

- CONTRIBUTING.md
> [Improvement][docs] Fix typo in CONTRIBUTING.md

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
with ONLINE process definition Add button should disabeld for readOnly
> [FIX][UI]add button disabeld when isDetails

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CollectionUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CommonUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ConnectionUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DependentUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/EncryptionUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/EnumUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/IOUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/IpUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/LoggerUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/Preconditions.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/PropertyUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/RetryerUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/SchemaUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/SensitiveLogUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StreamUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StringUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/TaskParametersUtils.java
*Add UnsupportedOperationException for utils construct to avoid the construct of utils and improvement the robust of code*
- *All utils in common module, add the UnsupportedOperationException in every utils construct*
> [Improvement][common] Add UnsupportedOperationException for utils construct

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/ServiceModelToSwagger2MapperImpl.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/resources/filter/ResourceFilter.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UdfFuncService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AccessTokenServiceImpl.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ResourcesControllerTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/dto/resources/filter/ResourceFilterTest.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/future/TaskFuture.java
#3639 
Remove some un-used code
UnNeed
> [Improvement][ALL] Remove some un-used code and code review #3639

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingClient.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingServer.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/NettyUtils.java
use EpollServerSocketChannel when system is linux
>  [improvement][remote]use EpollServerSocketChannel when system is linux

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/Constants.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/NettyUtils.java
linux platform default use epoll
> [Improvement][remote] linux platform default use epoll

- dolphinscheduler-dist/release-docs/LICENSE
- dolphinscheduler-dist/release-docs/licenses/ui-licenses/LICENSE-element-ui
- dolphinscheduler-ui/build/config.js
- dolphinscheduler-ui/package.json
- dolphinscheduler-ui/src/js/conf/home/index.js
- dolphinscheduler-ui/src/js/conf/login/index.js
> [feature-3665][ui]Add element-ui

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingServer.java
- dolphinscheduler-remote/src/test/java/org/apache/dolphinscheduler/remote/NettyUtilTest.java
update netty util test and fix init channel error
> [Test][remote]update netty util test and fix init channel error

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingClient.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/config/NettyClientConfig.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/Constants.java
- dolphinscheduler-remote/src/test/java/org/apache/dolphinscheduler/remote/NettyUtilTest.java
[Improvement][remote] set connect time out
> [Improvement][remote] set connect time out

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
[FIXBUG][common]fix yarn applications status cause NPE
*(or)*
(or)
*(example:)*
>  [FIXBUG][common]fix yarn applications status cause NPE(#3645)

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/versions.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
*Workflow version control ui optimize (#3612 )*
- *version.vue fix the `1` `2` `3` `4` `5` in issue #3612 *
> [Improvement-3612][ui] Workflow version control ui optimize

- dolphinscheduler-dist/release-docs/LICENSE
- dolphinscheduler-dist/release-docs/licenses/ui-licenses/LICENSE-@form-create-element-ui
- dolphinscheduler-ui/package.json
- dolphinscheduler-ui/pom.xml
- dolphinscheduler-ui/src/js/conf/home/index.js
- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/warningGroups/_source/list.vue
- dolphinscheduler-ui/src/js/conf/login/index.js
> [Feature-3682][ui]Add form-create plug-in and alarm group management add sample demo

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/pre_tasks.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
* Set pre-tasks to get current node connect to pre-nodes automatically.
* Only SHELL and SUB-PROCESS node enabled this method.
This closes [#3701](https://github.com/apache/incubator-dolphinscheduler/issues/3701)
> [Feature-3701][ui] Shortcut connection action for node in same flow

- .github/workflows/ci_e2e.yml
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/LogUtils.java
Fixed a bug introduced by Pull Request #3629
Fixed e2e build error
> [Bug][server]  fix 3629  pull request

- dolphinscheduler-ui/src/js/conf/home/pages/user/pages/password/_source/info.vue
#3722
fix cannot change password on dev branch.
> [Bug-3722][ui]fix cannot change password on dev branch. 

- pom.xml
- tools/dependencies/known-dependencies.txt
druid The lower version is not compatible with LocalDateTime
https://github.com/alibaba/druid/issues/3490
https://github.com/alibaba/druid/issues/3170
> [Improvement][DAO] druid The lower version is not compatible with LocalDateTime(DRUID 低版本不支持LocalDateTime)

- docker/build/Dockerfile
Dockerfile use apk --no-cache
Dockerfile use COPY 
*(or)*
(or)
*(example:)*
> fix:Dockerfile user apk --no-cache

- dolphinscheduler-dist/release-docs/LICENSE
- dolphinscheduler-dist/release-docs/licenses/ui-licenses/LICENSE-dagre
- dolphinscheduler-ui/package.json
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.js
The frontend introduces the dagre library, and uses the layered graph drawing algorithm to calculate the position of each task node
- *Add dagre:0.8.5 to package.json*
- *Add dagre info to LICENSE file*
- *Add LICENSE-dagre new file*
- *Modify dag.js reformat logic*
before
after
> [Improvement][ui] Refactored dag formatting logic

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/mr.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/python.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/shell.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/spark.vue
> [fixbug-3719][ui]Remove non-existent or deleted resources disabled

- docker/docker-swarm/docker-compose.yml
*[Fix-#3238][docker]Fix that can not create folder in docker with standalone mode*
*[Fix-#3238][docker]Fix that can not create folder in docker with standalone mode*
> [Fix-#3238][docker]Fix that can not create folder in docker with standalone mode

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/util.js
> [Improvement-3720][ui] js mailbox verification fix

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/Constants.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/Host.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/HostWeight.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistry.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobinTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/RandomSelectorTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/RoundRobinSelectorTest.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/HostTest.java
- pom.xml
load balance warm up
Verify this pull request
This pull request is already covered by existing tests, such as (please describe tests).
> [Improvement][remote]load balance warm up 

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/TaskParams.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/VarPoolUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/VarPoolUtilsTest.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessInstance.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstance.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskExecuteResponseCommand.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/TaskResponseProcessor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseEvent.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseService.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractTask.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/python/PythonTask.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/VarPoolUtilsTest.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
- pom.xml
- sql/dolphinscheduler-postgre.sql
- sql/dolphinscheduler_mysql.sql
- sql/upgrade/1.3.3_schema/mysql/dolphinscheduler_ddl.sql
- sql/upgrade/1.3.3_schema/postgresql/dolphinscheduler_ddl.sql
Content of PR:
Added VarPool:
Introduction: VarPool is similar to a global variable whose value can be dynamically modified. Variables are passed between different nodes in the task flow.
Difference: Global variables are constant attributes of the task flow, and currently there is no interface that can be dynamically modified.
Precautions:
Need to add the field var_pool in the t_ds_task_instance and t_ds_process_instance tables in the DB, the type is longtext.
How to use:**(Currently only supports Python nodes)**
Value: Just declare the variable name at LocalParams of the node.
Modification: ${setShareVar(variable name, value)} in the script.
Example:
Node a1:
Script:
value = 600 + 60
${setShareVar(${shareVar1},value+6)}
Node a2:
Custom parameters:
shareVar1:"default"
Script: …
> [Feature]Add Python task "task variable / result transfer" implementation

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
- sql/dolphinscheduler-postgre.sql
- sql/dolphinscheduler_mysql.sql
- sql/upgrade/1.3.3_schema/mysql/dolphinscheduler_ddl.sql
- sql/upgrade/1.3.3_schema/postgresql/dolphinscheduler_ddl.sql
*Cherry pick from dev to fix that create folder duplicate name under multithreading*
fix issue #3487
*Cherry pick from dev to fix that create folder duplicate name under multithreading*
> [Fix-#3487][api、dao] Cherry pick from dev to fix that create folder duplicate name under multithreading

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
> [Improvement][API] simplify with stream

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/HostWeight.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobin.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobinTest.java
lower weight round robin  support weight
> [Improvement][server]lower weight round robin  support weight

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TenantService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TenantControllerTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
* Bugfix: Fix the new tenant already exists prompt
fix issue #3131
> [Hotfix-3131][api] cherry-pick from  dev to fix the new tenant already exists prompt (#3132)

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
*When re-upload the resource file but don't change the name or desc,it need replace the origin resource file.*
*When re-upload the resource file but don't change the name or desc,it need replace the origin resource file.*
> [Fix-#3702][api] When re-upload the resource file but don't change the name or desc,it need replace the origin resource file.

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
> [fixbug-3621][ui]Workflow instance ready to stop and ready to suspend state prohibits checking

- dolphinscheduler-api/pom.xml
Fix log dependency package conflict (slf4j-log4j12、logback)
Add exclusion for slf4j-log4j12
> [Fix][API] Log dependency package conflict

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/zk/ZKMasterClient.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
- dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
- pom.xml
fix bug(#3617 ) refactor the subtask process, fix 2 tasks instance are generated when fault tolerance.
> [FIX-3617][Service]fix 2 tasks instance are generated when fault tolerance

- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
fix bug(#3573) potential horizontal unauthorized access
> [FIX-3573][DAO] potential horizontal unauthorized access

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/createTenement.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
> [fixbug-3887][ui]Fix missing English translation of re-upload files

- sql/upgrade/1.3.3_schema/mysql/dolphinscheduler_dml.sql
- sql/upgrade/1.3.3_schema/postgresql/dolphinscheduler_dml.sql
*[Fix-#3487][sql] add dolphinscheduler_dml.sql under 1.3.3_schema*
*[Fix-#3487][sql] add dolphinscheduler_dml.sql under 1.3.3_schema*
> [Fix-#3487][sql] add dolphinscheduler_dml.sql under 1.3.3_schema

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
> [fixbug-3621][ui]Repair check box cannot be canceled

- dolphinscheduler-dist/src/main/assembly/dolphinscheduler-binary.xml
```xml
...
```
```xml
...
```
*(or)*
(or)
*(example:)*
> fix service comment

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
> [fixbug-3924][ui]Workflow definition name re-modified and added check

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
fix #3843
1.When update workflow definition,first verify the name of the workflow definition, save the data.
2.Be consistent with the dev branch code
udp.vue
> [1.3.3-release][fix-#3843][api]When update workflow definition,first verify the name of the workflow definition, save the data

- dolphinscheduler-alert/pom.xml
- dolphinscheduler-api/pom.xml
- dolphinscheduler-common/pom.xml
- dolphinscheduler-dao/pom.xml
- dolphinscheduler-dist/pom.xml
- dolphinscheduler-plugin-api/pom.xml
- dolphinscheduler-remote/pom.xml
- dolphinscheduler-server/pom.xml
- dolphinscheduler-service/pom.xml
- dolphinscheduler-ui/pom.xml
- pom.xml
*change version from 1.3.2-SNAPSHOT to 1.3.3-SNAPSHOT*
*change version from 1.3.2-SNAPSHOT to 1.3.3-SNAPSHOT*
> change version from 1.3.2-SNAPSHOT to 1.3.3-SNAPSHOT

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
> [fixBug-3964][ui]Switch back and forth over timeout alarm, the selected value is empty

- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
fix https://github.com/apache/incubator-dolphinscheduler/issues/3618
> [fix-3618]solve too many files, close logClientService

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/log/TaskLogAppender.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractTask.java
- dolphinscheduler-server/src/main/resources/logback-worker.xml
*[Fix-#3618][server] resolve task executed finished but not release the file handle*
*[Fix-#3618][server] resolve task executed finished but not release the file handle*
- *Add TaskLogAppender*
> [Fix-#3618][server] resolve task executed finished but not release the file handle

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
*[Fix-#3958][api] files should not be created successfully in the directory of the authorized file*
*add the judge of whether has permission*
> [Fix-#3958][api] files should not be created successfully in the directory of the authorized file

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Command.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/DependentTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterBaseTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/SubProcessTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/AlertManager.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/DependentExecute.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
fix (#3966 ) sub_process The timeout warning does not take effect.
add timeout warning for sub_process/dependent task.
fix (#3974) The child process does not inherit the worker group of the parent process
> [FIX-3966] The timeout warning does not take effect in sub_process

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/CommandStateCount.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/TaskCountDto.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/TaskStateCount.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataAnalysisServiceTest.java
#3557
- full cover ```DataAnalysisServiceImpl```
- simplify ```DataAnalysisServiceImpl```  internal method
- delete try catch that will not throw any exeception
> [Test-3557][API] full cover DataAnalysisServiceImpl

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
fix bug (#4010): remove failed condition tasks from error-task-list.
> [FIX-4010][SERVER] remove failed condition tasks from error-task-list.

- script/dolphinscheduler-daemon.sh
Improvement daemon script usage .
> [Improvement][script] daemon script usage

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/conditions/ConditionsParameters.java
Fix NullPointerException when save condition task.
[ProcessDefinitionServiceImpl.java#L242](https://github.com/apache/incubator-dolphinscheduler/blob/dev/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java#L242)
changes:
Return empty List\<ResourceInfo\> at org.apache.dolphinscheduler.common.task.conditions.ConditionsParameters#getResourceFilesList
for example:
[SubProcessParameters.java#L47](https://github.com/apache/incubator-dolphinscheduler/blob/dev/dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/subprocess/SubProcessPar …
> [Fix][API] Condition task NullPointerException

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/SparkArgsUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/spark/SparkTask.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/spark/SparkTaskTest.java
*#4050 Spark Task support user define vars inject*
- *Modify SparkTask & SparkArgsUtils*
- *worker/SparkTaskTest*
> [Feature-4050][server] Spark task support udv inject

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StringUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/StringUtilsTest.java
#4098 Method needs to determine if it is null, otherwise an exception will be reported
> fix replaceNRTtoUnderline NullPointerException #4098

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseService.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseServiceTest.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
- pom.xml
Concurrent processing of ack message and result message causes the execution sequence to be wrong
Optimize code and reduce database queries
this close #4084
> [FIX-#4084][server]fix taskInstance state change error

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/WorkerGroupService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/WorkerGroupServiceTest.java
#4109  ignore noNodeException when get worker groups
>  [Improvement][API] ignore noNodeException when get worker groups

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorService2Test.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/MasterExecThreadTest.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
- dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
fix spell "WAITTING" to "WAITING"
"CMDPARAM_"   to  "CMD_PARAM_"
Add "@Override" annotations to the necessary methods
> [Improvement][Code style] FIX SPELL WAITTING TO WAITING , etc.

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StringUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/placeholder/TimePlaceholderUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/ParameterUtilsTest.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/placeholder/TimePlaceholderUtilsTest.java
- pom.xml
We currently only use this symbol for dates, so I filtered out the number type.
this close #4033
> [FIX#4033] $[] conflicts with mysql keywords

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StringUtils.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/placeholder/TimePlaceholderUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/ParameterUtilsTest.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/placeholder/TimePlaceholderUtilsTest.java
- pom.xml
*cherry pick from dev to resolve that `$[]`` conflicts with mysql keywords*
*cherry pick from dev to resolve that `$[]`` conflicts with mysql keywords*
*ParameterUtilsTest*
*TimePlaceholderUtilsTest*
> [FIX#4033]cherry pick from dev to resolve that `$[]`` conflicts with mysql keywords

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java
*[Fix-4090][dao] Cherry pick from dev to add null judgment*
*[Fix-4090][dao] Cherry pick from dev to add null judgment*
> [Fix-#4090][dao] Cherry pick from dev to add null judgment

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/ProcessUtilsTest.java
*[FIX-3900][server] Cherry pick from dev to kill multi yarn app in one job*
*modify server/utils/ProcessUtils.java cancelApplication method*
*server/utils/ProcessUtilsTest to verify this pr*
> [FIX-3900][server] Cherry pick from dev to kill multi yarn app in one job

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseService.java
*[FIX-#4084][server]cherry pick from dev to fix taskInstance state change error*
*[FIX-#4084][server]cherry pick from dev to fix taskInstance state change error*
> [FIX-#4084][server]cherry pick from dev to fix taskInstance state change error

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/DBTaskAckCommand.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/DBTaskResponseCommand.java
fix  #4125 , DBTaskAckCommand and DBTaskResponseCommand add construction method！
> fix bug #4125

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseService.java
> cherry-pick task_ack_miss

- docker/build/Dockerfile
- docker/build/README.md
- docker/build/README_zh_CN.md
- docker/build/conf/dolphinscheduler/common.properties.tpl
- docker/build/conf/dolphinscheduler/datasource.properties.tpl
- docker/build/conf/dolphinscheduler/zookeeper.properties.tpl
- docker/build/startup-init-conf.sh
- docker/build/startup.sh
- docker/docker-swarm/docker-compose.yml
- docker/docker-swarm/docker-stack.yml
*Some parameters were improved for Docker*
*Some parameters were improved for Docker*
- *Remove the step of installing kazoo*
- *add `DATABASE_TYPE` to support more db*
- *set the default value of `DOLPHINSCHEDULER_RESOURCE_STORAGE_TYPE`、`DOLPHINSCHEDULER_FS_DEFAULTFS`*
*The docs of how to build and run fro docker*
- *docker/build/README.md*
- *docker/build/README_zh_CN.md*
> [Improve-4143][docker]Some parameters were improved for Docker

- dolphinscheduler-ui/src/js/module/components/crontab/source/_times/day.vue
- dolphinscheduler-ui/src/js/module/components/crontab/source/util/index.js
*[Feature-#4054][UI]Repair the last Sunday of each month*
*[Feature-3878][UI]Repair the last Sunday of each month*
> [Fix-4054][UI]Repair the last Sunday of each month

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumer.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumerTest.java
*[Feature-4138][Master]Cherry pick from dev to dispatch add sleep when dispatch task to work error*
*[Feature-4138][Master]Cherry pick from dev to dispatch add sleep when dispatch task to work error*
*Run TaskPriorityQueueConsumerTest.java*
> [Feature-4138][Master]Cherry pick from dev to dispatch add sleep when dispatch task to work error

- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java
fix #4218: start from the setting nodes withe NODE_PRE would be an NPE.
> [FIX-4218][MASTER]: start from the setting nodes with NODE_PRE would be NPE.

- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
deleted the code at following two places:
org.apache.dolphinscheduler.service.process.ProcessService#checkTaskExistsInTaskQueue
org.apache.dolphinscheduler.service.process.ProcessService#taskZkInfo
> deleted invalid code as assigned in issue 4215

- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/pom.xml
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannel.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannelFactory.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertConstants.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertPlugin.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSender.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannelFactoryTest.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannelTest.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertPluginTest.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSenderTest.java
- dolphinscheduler-alert-plugin/pom.xml
- pom.xml
- *add dolphinscheduler-alert-http module.*
- *add http alert plugin UT*
- *modify root pom *
this close #4027
> [Alert plugin design] add http alert plugin

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/shell/ShellTask.java
rerun schedule time error
this closes #3177
> [FIX-#3177]Task time parameter parsing error

- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
#3940  fix  sql Grammar mistakes
> fix sql error

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/shell/ShellTask.java
when system.datetime !=null $[datetime] = system.datetime
else $[datetime] = current time
> [FIX-3177]Task time parameter parsing error

- dolphinscheduler-ui/src/js/conf/home/App.vue
- dolphinscheduler-ui/src/js/conf/home/index.js
- dolphinscheduler-ui/src/js/module/io/index.js
- dolphinscheduler-ui/src/js/module/visibility/index.js
- **fix re-login problem in new tab**
- **fix state synchronization problem in multiple tabs**
- 1e5da637 fix(ui): re-login problem in new tab
- afeec6ca refresh page in new tab automatically
- 72e63d26 support to reload router view in lightweight
The new re-login condition is `(!sIdCookie || (sessionId && sessionId !== sIdCookie)) && requstUrl !== 'login'`
assume `requstUrl !== 'login'`:
- `sIdCookie` is `undefined` or `null`: require re-login
- `sessionId && sessionId !== sIdCookie`: require re-login when sessionId changed
- attention that `sessionId` may be `null` but `sIdCookie` is non-empty
And, the state …
> [Fix][UI]: fix re-login problem in new tab and state synchronization problem in multiple tabs

- dolphinscheduler-ui/.eslintrc.yml
- dolphinscheduler-ui/package.json
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/mr.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/python.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/shell.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/spark.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sqoop.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/waterdrop.vue
- dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/createDataSource.vue
- dolphinscheduler-ui/src/js/module/axios/jsonp.js
- dolphinscheduler-ui/src/js/module/axios/querystring.js
- dolphinscheduler-ui/src/js/module/components/transfer/resource.vue
- dolphinscheduler-ui/src/js/module/util/localStorage.js
*Add no-var rule for eslint and add `npm run lint:fix` command*
- *Add no-var rule for eslint, and fix related files*
- *Add `npm run lint:fix` command, which distinguished from the default command `npm run lint`*
- The behavior of command `npm run lint` and command `npm run lint:fix` should be distinguished
- The first command is used to lint only, and the second one is used to lint and fix problems automatically
This pull request is already covered by existing tests.
> [Improvement][UI] Add no-var rule for eslint and add `npm run lint:fix` command

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/list.vue
database date :
error page 
fix page
> [FIX][UI ]  security user state  tenantCode User Type Display abnormal

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/exceptions/TaskPriorityQueueException.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/PeerTaskInstancePriorityQueue.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/TaskPriorityQueue.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/TaskPriorityQueueImpl.java
- dolphinscheduler-service/src/test/java/queue/PeerTaskInstancePriorityQueueTest.java
- pom.xml
*[Fix-4222][Master]Add the priority queue to ensure that tasks are submitted according to priority.*
*[Fix-4222][Master]Add the priority queue to ensure that tasks are submitted according to priority.*
- *Replace map with priority queue in MasterExecThread*
- *Add PeerTaskInstancePriorityQueueTest*
- *Add PeerTaskInstancePriorityQueue*
*PeerTaskInstancePriorityQueueTest*
> [Fix-4222][Master]Add the priority queue to ensure that tasks are submitted according to priority.

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractTask.java
remove AbstractTask.getCurTaskParamsClass()and replace with TaskParametersUtils.getParameters()
this closes #1682
> remove AbstractTask.getCurTaskParamsClass()and replace with TaskParametersUtils.getParameters()

- dolphinscheduler-dao/src/main/resources/datasource.properties
[新增]元数据mysql连接模版
*(or)*
(or)
*(example:)*
> [improvement][config] Update datasource.properties，add mysql meta data template

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/_source/list.vue
#4273 
Fix the submission time of task instance is empty
> [fix-4273][UI] The submission time of task instance is empty

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/list.vue
> [Improvement-3878]Tenant list delete user name

- dolphinscheduler-api/pom.xml
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/AppConfiguration.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AlertGroupController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TenantController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkFlowLineageController.java
- pom.xml
- tools/dependencies/known-dependencies.txt
this closes #4268 
- *Fix example missing in ApiImplicitParam and unreasonable syntax*
- *Replace the default version of swagger-models imported by springfox-swagger2 with higher version, because the default version has the bug of NumberFormatException*
**GIF Verify**:
> [Fix-4268] Fix NumberFormatException when visiting a doc.html or swagger-ui.html

- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/function/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/resource/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/subUdfDirectory/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/queue/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/warningGroups/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/workerGroups/_source/list.vue
- dolphinscheduler-ui/src/sass/common/_table.scss
> [Improvement-3878][ui]Fix the list style

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/list/_source/createProject.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/list/index.vue
fix create project cancel button invalid
> [FIX] [UI] fix create project cancel button invalid

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/codec/NettyDecoder.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/codec/NettyEncoder.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/Command.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/CommandContext.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/CommandHeader.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumer.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterBaseTaskExecThread.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterSchedulerService.java
- dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumerTest.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/TaskPriority.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/TaskPriorityQueueImpl.java
- dolphinscheduler-service/src/test/java/queue/TaskPriorityTest.java
- dolphinscheduler-service/src/test/java/queue/TaskUpdateQueueTest.java
- Refactor code to support tracing 
- Extension network protocol, support context and version
- Extension master asynchronous queue support context
- Extract scan task method from MasterSchedulerService for tracing
- *Update Test case to verify the change.*
> [Improvement] Refactor code to support distributed tracing

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ArgsUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtils.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/LogUtils.java
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
this closes #4289
- *fix flink name not display in process definition editor*
- *fix flink name not escape problem*
(or)
*(example:)*
> [Fix-4289][*] Flink name with disappeared and unescaped problem

- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapper.xml
this closes #4294 
fix the database field of the t_ds_udfs table is the mysql DB keyword
add the alias for the t_ds_udfs table
> [fix-4294][dao] The database field of the t_ds_udfs table is the mysql DB keyword

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/versions.vue
this closes #4306 
Fix the closing function of version information
Add close function
> [fix-4306][UI] The version information closing function does not take effect

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/plugin/AlertPluginManager.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UiPluginController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UiPluginService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UiPluginServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UiPluginServiceTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/PluginType.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/PluginDefineMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/PluginDefineMapper.xml
- pom.xml
*Some plugins (such as alert plugin) need to provide UI interfaces to users.
*We use from-creat to dynamically generate UI interfaces. Related parameters are mainly provided by pluginParams.
*From-create can generate dynamic ui based on this parameter.
this closes #4310
> [Feature#4310][Alert-SPI] Plug-ins containing UI components provide display pages

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/config.js
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.scss
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/log.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/scriptBox.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/datax.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/python.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/shell.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sql.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sqoop.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/plugIn/jsPlumbHandle.js
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/index.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
**Improve script box and dialog css style**
- *Improve script box and dialog css style*
*(example:)*
**Before fix**:
**After fix**:
> [Improvement][UI] Improve script box and dialog css style

- dolphinscheduler-ui/src/js/module/filter/filter.js
Fix invalid date problem in IE
This closes #4338
- *Modify formatDate in dolphinscheduler-ui/src/js/module/filter/filter.js*
*(example:)*
After fix:
> [FIx-4338][UI] Fix invalid date problem in IE

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
- dolphinscheduler-api/src/main/resources/i18n/messages.properties
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
1. Increase "queryProcessDefinitionByName" API.
2. Will queryProcessDefinitionById api "PROCESS_INSTANCE_EXIST" state is modified to "PROCESS_DEFINE_NOT_EXIST".
> [Improvement-4257][api]  Increase "queryProcessDefinitionByName" API

- README.md
- README_zh_CN.md
This pull request modified the readme.md file by deleting "online demo" part.
this closes #4391
> readme file fixed

- dolphinscheduler-ui/src/js/module/components/secondaryMenu/_source/menu.js
- dolphinscheduler-ui/src/js/module/components/secondaryMenu/secondaryMenu.vue
Rename `disabled` to `enabled` in menu and improve code readability
Rename disabled to enabled in menu
This pull request is already covered by existing tests
> [Improvement][UI] Rename disabled to enabled in menu

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorService2Test.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/ParameterUtilsTest.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
- dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
#130
Could pass global param values when starting a new process instance.
The main idea is to merge the start param values into the new process instance's global params.
- add optional param for start-process-instance api
- reuse command_param in command table for persistence
- overload curingGlobalParams function in ParameterUtils
- not adapt the UI code yet
-  Added test case in ParameterUitlsTest
-  Added test case in ProcessServiceTest to verify the start param value could be  merged into new process instance's global params
- Manually verified the start-process-instance API by testing locally
The test process definition json as below 
`{"globalParams":[{"prop":"tenant_id","direct":"IN","type":"VARCHAR","value":""}],"tasks":[{"typ …
> [Feature-#130] pass global param values when starting new process instance

- dolphinscheduler-api/pom.xml
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/SnowFlakeUtils.java
- dolphinscheduler-common/src/main/resources/common.properties
- dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/SnowFlakeUtilsTest.java
add snow flake. we can use it like SnowFlakeUtils.getInstance().nextId() .But you should need to handle the exception
> [Feature][JsonSplit] snowFlakeUtils

- dolphinscheduler-ui/src/js/conf/home/App.vue
- dolphinscheduler-ui/src/js/conf/home/router/index.js
*Correct spelling mistakes*
- *Rename `refesh_in_switched_tab` to `refresh_in_switched_tab`*
> [Improvement][UI] Correct spelling mistakes

- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/DataSourceMapper.xml
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ResourceMapper.xml
- dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
- dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
*fixed issue #4428*
this closes #4428
- *dao module modify  DataSourceMapper.xml and ResourceMapper.xml *
- *UI module add username and add userName in il8n*
> [Feature-4428][dao、UI] It is recommended to add an owner in the data source center and the Resource Center to make it easier to manage

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/manager/DingTalkManager.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/plugin/EmailAlertPlugin.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/template/AlertTemplateFactory.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/template/impl/DefaultHTMLTemplate.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/Constants.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/DingTalkUtils.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtils.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/ExcelUtils.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/FuncUtils.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/MailUtils.java
- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/PropertyUtils.java
- dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/DingTalkUtilsTest.java
- dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/ExcelUtilsTest.java
- dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/PropertyUtilsTest.java
This pull request fixes some of the code smell and vulnerability reported by sonar
Fixes part of #3325 
- *Refactor files to fix code smell and vulnerability reported by sonar in the alert module*
> [Improvement][alert] Refactor alert module to fix code smell

- docker/build/hooks/build
- docker/build/hooks/push
- mvnw
> fix: use shellformat(shfmt) and shellcheck fix mvnw

- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
> [FIX-4247][Api]Fixed the problem that the global parameters are not updated after the workflow instance click rerun

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataSourceController.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/BaseService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/BaseServiceTest.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StringUtils.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/BaseDataSource.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/HiveDataSource.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SQLServerDataSource.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SparkDataSource.java
this PR closes #4435 
the datasource tests the connection and returns details when the connection is wrong
- BaseDataSource add getConnection
> [Improvement-4435][datasource] the datasource tests the connection and returns details when the connection is wrong

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/AlertGroupService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/BaseService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/QueueService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/WorkerGroupService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
issue #4480 
for the better understand of method 'checkAdmin' in class BaseService.
- Modify the method's name 'checkAdmin' to 'isNotAdmin' in class BaseService 
- Where we use this method
> [Improvement-4480][API] change method checkAdmin to isNotAdmin

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
ProcessDefinition create api  return ProcessDefinitionId  issue #4481
this close #4481
> [Improvement-#4481][API] ProcessDefinitionController save API optimization

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/kinship/index.vue
this close #4468
version-dev no release
The ID list has no valid incoming back-end service
> [FIX-#4468] [UI] Workflow relationships Name filtering invalidated

- NOTICE
- dolphinscheduler-dist/release-docs/NOTICE
*Update year to 2021*
*Update year to 2021*
> [NOTICE Update]Update year to 2021

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/PropertyUtils.java
- dolphinscheduler-alert/src/main/resources/alert.properties
fix alert property utils init properties.
> [Fix][alert] fix alert property utils init properties.

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/list.vue
fix ui user authorization dialog
> [BUG][UI] fix ui user authorization dialog

- dolphinscheduler-alert-plugin/dolphinscheduler-alert-dingtalk/src/main/java/org/apache/dolphinscheduler/plugin/alert/dingtalk/DingTalkParamsConstants.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-dingtalk/src/main/java/org/apache/dolphinscheduler/plugin/alert/dingtalk/DingTalkSender.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailConstants.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/MailParamsConstants.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/MailSender.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/exception/AlertEmailException.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/template/DefaultHTMLTemplate.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-script/src/main/java/org/apache/dolphinscheduler/plugin/alert/script/OSUtils.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-script/src/main/java/org/apache/dolphinscheduler/plugin/alert/script/StreamGobbler.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-wechat/src/main/java/org/apache/dolphinscheduler/plugin/alert/wechat/WeChatAlertConstants.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-wechat/src/main/java/org/apache/dolphinscheduler/plugin/alert/wechat/WeChatAlertParamsConstants.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-wechat/src/main/java/org/apache/dolphinscheduler/plugin/alert/wechat/WeChatSender.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-wechat/src/main/java/org/apache/dolphinscheduler/plugin/alert/wechat/exception/WeChatAlertException.java
- dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/utils/JSONUtils.java
This pull request fixes some of the code smell and vulnerability reported by sonar
Fixes part of #3325 
- *Refactor files to fix code smell and vulnerability reported by sonar in the alert-plugin module*
> [Improvement][alert-plugin] Refactor alert-plugin module to fix code smell

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/queue/_source/createQueue.vue
- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/createTenement.vue
- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
- dolphinscheduler-ui/src/js/conf/home/pages/user/pages/token/_source/createToken.vue
fix ui createToken submit error.
> [BUG][UI] fix ui createToken submit error.

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/index.vue
- dolphinscheduler-ui/src/js/module/util/routerUtil.js
> [Improvement-4556][ui]Repair the workflow instance, click the browser to return to the previous page, always start the query from the first page

- sql/upgrade/1.4.0_schema/mysql/dolphinscheduler_ddl.sql
- sql/upgrade/1.4.0_schema/postgresql/dolphinscheduler_ddl.sql
> [BUG][schema] fix schema 1.4.0

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/plugIn/jsPlumbHandle.js
> [fixbug-4570][ui] When deleting a workflow connection, all connections disappear

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
this PR close #4573 
Adds prompt message to DAG page button
> [Improvement-4573][UI] Adds prompt message to DAG page button

- dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/runner/AlertSender.java
- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
> [Fix][Alert]fix alert server client send.

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
add code in task model
refer to #4417
> [Feature][JsonSplit] [ui] add code in task model

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionLogMapper.java
- dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionLogMapper.xml
- dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
add processdefinition create/delete method
#4417
> [Feature][JsonSplit] modify processdefinition create/delete method

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/log.vue
- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/plugIn/jsPlumbHandle.js
- dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/_source/zookeeperList.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/index/_source/taskStatusCount.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/index.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/_source/list.vue
- dolphinscheduler-ui/src/js/module/components/secondaryMenu/_source/menu.js
- dolphinscheduler-ui/src/sass/common/index.scss
> [Improvement][ui] Front-end interface optimization

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java
> [1.3.5-prepare][cherry-pick]#4272 Fix IOException or NoSuchFileException in logger server 

- dolphinscheduler-api/src/main/resources/application-api.properties
> [1.3.5-prepare][cherry-pick]#4121 enable response resources gzip compression 

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
> [1.3.5-prepare][cherry-pick]#4459 update workflow instance NPE

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/log.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/details/index.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/subdirectory/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/resource/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/subUdfDirectory/_source/list.vue
- dolphinscheduler-ui/src/js/module/download/index.js
- dolphinscheduler-ui/src/js/module/permissions/index.js
> [1.3.5-prepare][cherry-pick]#4110 resolve download url and improve security page disappear delay problem under GENERAL_USER

- dolphinscheduler-ui/src/js/module/io/index.js
> [1.3.5-prepare][cherry-pick]#4162 fix re-login problem in new tab

- ambari_plugin/common-services/DOLPHIN/1.3.3/configuration/dolphin-worker.xml
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/WorkerGroupService.java
> [FIX-#4592]Fix that the worker group management IP is not displayed correctly.

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/shell/ShellExecutor.java
> [1.3.5-prepare][cherry-pick]#4456 fix parse shell output

- dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/index.vue
fix ui datasource dialog visible.
> [Fix][UI] fix ui datasource dialog visible.

- dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/pom.xml
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuAlertChannel.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuAlertChannelFactory.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuAlertPlugin.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuParamsConstants.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuSender.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/HttpRequestUtil.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/test/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuAlertChannelFactoryTest.java
- dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/test/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuSenderTest.java
- dolphinscheduler-alert-plugin/pom.xml
- dolphinscheduler-dist/src/main/provisio/dolphinscheduler.xml
- pom.xml
Realized the feishu  robot to send warning message
this closes #4350
Test the screenshot：
> [Feature-#4350][Alert]support feishu plugin

- .asf.yaml
> update project description

- .asf.yaml
update project desc
*(or)*
(or)
*(example:)*
> update project desc

- sql/upgrade/1.3.3_schema/postgresql/dolphinscheduler_ddl.sql
- sql/upgrade/1.4.0_schema/postgresql/dolphinscheduler_ddl.sql
Fix postgresql sql script syntax error.
- *Update sql/upgrade/1.3.3_schema/postgresql/dolphinscheduler_ddl.sql*
- *Update sql/upgrade/1.4.0_schema/postgresql/dolphinscheduler_ddl.sql*
> [Fix][sql] Postgresql upgrade script error

- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingClient.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingServer.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/codec/NettyEncoder.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskKillResponseCommand.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/exceptions/RemoteException.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/future/ResponseFuture.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/handler/NettyClientHandler.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/handler/NettyServerHandler.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/ChannelUtils.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/Constants.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/IPUtils.java
- dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/Pair.java
This pull request fixes some of the code smell and vulnerability reported by sonar
Fixes part of #3325 
- *Refactor files to fix code smell and vulnerability reported by sonar in the remote module*
> [Improvement][remote] Refactor remote module to fix code smell

- dolphinscheduler-common/src/main/resources/common.properties
In order to prevent user operation errors, I added a clearer comment to the system env path of common.properties.
No verification required
> [Feature-4596] Add a description for the system env path in common.properties

- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/_source/common.js
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/details/index.vue
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/edit/index.vue
**Support more file types in file detail page**
- *Support more file types in file detail page*
*(example:)*
> [Improvement][UI] Support more file types in file detail page

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
This closes #4648
It can be cherry-picked into `1.3.5-prepare`
@break60 @CalvinKirs 
> [Fix-4648][UI] Fix TypeError: Cannot read property 'id' of undefined in createUser

- dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/localParams.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/start.vue
fix ui local param plugin do not display input.
> [Fix][UI]fix ui local param plugin do not display input.

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
- dolphinscheduler-ui/src/js/module/components/transfer/resource.vue
> [cherry-pick-4649][UI] Fix TypeError: Cannot read property 'id' of undefined in createUser

- dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
- dolphinscheduler-ui/src/js/module/components/transfer/resource.vue
> [Improvement-4504][ui]Fix too many resources to display

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/AppConfiguration.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/interceptor/LocaleChangeInterceptor.java
- dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/interceptor/LocaleChangeInterceptorTest.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-ui/package.json
- dolphinscheduler-ui/src/js/module/io/index.js
- pom.xml
> [1.3.5-prepare][cherry-pick]#4490 improve cors (#4439)

- docker/build/Dockerfile
- docker/build/README.md
- docker/build/README_zh_CN.md
- docker/build/conf/dolphinscheduler/common.properties.tpl
- docker/build/conf/dolphinscheduler/logback/logback-alert.xml
- docker/build/startup-init-conf.sh
- docker/build/startup.sh
- docker/docker-swarm/docker-compose.yml
- docker/docker-swarm/docker-stack.yml
**[Improvement][Docker] update outdated readme and fix PSQLException**
This closes #4651
- *Update outdated readme*
- *Fix PSQLException*
> [1.3.5-prepare][docker] update outdated readme and fix PSQLException

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/conditions/ConditionsParameters.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
- dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
It solves the problem that the name of the branch will not change after the name of the branch is changed in the workflow page and instance page.
pr #4555
issue #2101
> [1.3.5-prepare][cherry-pick]#4555 update branch name error

- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
- dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/conditions/ConditionsParameters.java
- dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
- dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Reverts apache/incubator-dolphinscheduler#4662
> Revert "[1.3.5-prepare][cherry-pick]#4555 update branch name error"

- dolphinscheduler-dao/src/main/resources/datasource.properties
**Remove duplicated mysql configurations**
- Remove duplicated mysql configurations
*(example:)*
> [Improvement][Dao] Remove duplicated mysql configurations

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtils.java
Fix flink `-yn` option missing after upgrading
> [Fix][Flink] Fix flink -yn option missing after upgrading

- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/_source/taskRecordList/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
- dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/_source/list.vue
ui improvement. Change the no to taskinstance, processinstance, processdefinition id
Change the no to taskinstance, processinstance, processdefinition id
ui improvement. check projects page ui
> Improvement/UI no #3725

- dolphinscheduler-ui/src/js/module/io/index.js
Create a new project the name contain "http"，If you enter the project process list, an Error 404 will be reported，and the interface of the new process will also report an Error 404, and the URL path of the front-end splicing is not correct
this closes #4640 
this closes #4672 
before change
```
const resolveURL = (url) => {
if (url.indexOf('http')  !== -1) {
return url
}
if (url.charAt(0) !== '/') {
return `${apiPrefix}/${url.replace(reSlashPrefix, '')}`
}
return url
}
```
after change
```
const resolveURL = (url) => {
if (url.indexOf('http')  === 0) {
return url
}
if (url.charAt(0) !== '/') {
return `${apiPrefix}/${url.replace(reSlashPrefix, '')}`
}
return url
}
```
*(or)*
This …
> [Fix-4640][UI] Fixed a 404 error when the project name contains "http"

- dolphinscheduler-ui/src/js/module/io/index.js
> [cherry-pick-#4688][UI] Fixed a 404 error when the project name contains "http" 

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/UDFUtils.java
> [1.3.5-prepare][cherry-pick]#4692 Fix udf jar path not exist when fs.defaultFS starts with file:/// (#4691)

- dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java
*This is my first PR. *
*Add comment*
This pull request is already covered by existing tests.
> [Improvement][server]Add comment

- docker/build/README.md
- docker/build/README_zh_CN.md
> [1.3.5-prepare][Improvement][Docker] Update readme

- dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
- dolphinscheduler-common/src/main/resources/common.properties
- dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/_source/common.js
Add more resource suffix
Match with [filtTypeArr](https://github.com/apache/incubator-dolphinscheduler/blob/dev/dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/_source/common.js#L21) in vue
*(example:)*
> [Improvement][Common] Sync resource suffix
